"""
Per-state SOS portal navigation instructions for browser-use agents.
Each entry provides step-by-step directions tailored to that state's
specific page layout so the LLM-driven browser agent can reliably
find the search box, submit a query, click the right result, and
locate officers/agents on the detail page.
"""

PORTAL_INSTRUCTIONS: dict[str, str] = {

    # ─── ALABAMA ───────────────────────────────────────────────
    "AL": (
        "The Alabama SOS portal is at www.sos.alabama.gov/government-records/"
        "business-entity-records. This is the landing page for the Government "
        "Records Inquiry System.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "The page shows 'Business Entity Search Options' with these hyperlinks:\n"
        "- 'Entity Name' — use this for company/LLC/Corp searches\n"
        "- 'Entity Number' — ignore\n"
        "- 'Officer | Agent | Incorporator' — use this for person-name searches\n"
        "- 'Reservation | Registration by ID' — ignore\n\n"
        "DECISION: If the search query is a business name (LLC, Inc, Corp, etc.), "
        "click 'Entity Name'. If the search query is a person's name, click "
        "'Officer | Agent | Incorporator'.\n\n"
        "Each search option opens in a NEW browser window/tab.\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "After clicking 'Entity Name', a search form appears with several filter "
        "fields. The only field that matters is the 'Name' field — type the entity "
        "name into it. Leave all other filters at their defaults. Click 'Search'.\n\n"
        "RESULTS: A new page loads with a list of matching entities. Each result "
        "shows an Entity ID as a clickable hyperlink, plus the entity name and "
        "status. Click the Entity ID hyperlink for the entity that best matches "
        "your search query.\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The detail page displays all entity information on a single page. "
        "Extract ALL of the following:\n\n"
        "ENTITY INFO:\n"
        "- Entity Name, Entity ID, Entity Type\n"
        "- Formation Date, Status (Active/Inactive/etc.)\n"
        "- Principal Address / Business Address\n\n"
        "REGISTERED AGENT:\n"
        "- Name and 'Registered Officer Address' — this is typically a BUSINESS "
        "address (office, not residential)\n\n"
        "DIRECTORS:\n"
        "- Each director is listed with their name and 'Street Address'\n"
        "- The director street address is likely a RESIDENTIAL address\n"
        "- Record each director with their name, title='Director', and full address\n\n"
        "INCORPORATORS:\n"
        "- Each incorporator is listed with their name and 'Street Address'\n"
        "- The incorporator street address is also likely a RESIDENTIAL address\n"
        "- Record each incorporator with name, title='Incorporator', and full address\n\n"
        "NOTE: The same person may appear as the Registered Agent, a Director, AND "
        "an Incorporator (e.g. Blue Bonnett Taco, Inc. has the same individual in "
        "all three roles). Record them ONCE but note all their roles/titles and "
        "capture BOTH the business address (from Registered Agent) and the "
        "residential address (from Director/Incorporator) as separate data points.\n\n"

        "═══ CRITICAL: NAME FORMAT ═══\n"
        "Alabama lists names in REVERSE ORDER: 'Last, First Middle' or "
        "'Last, First M.' (e.g. 'Smith, John Robert' or 'Doe, Jane A.').\n"
        "You MUST convert these to standard order: 'First Middle Last' or "
        "'First M. Last' (e.g. 'John Robert Smith' or 'Jane A. Doe') when "
        "recording them in the output."
    ),

    # ─── ALASKA ────────────────────────────────────────────────
    "AK": (
        "The Alaska CBPL search page has two search fields at the top of the page:\n"
        "1. 'Entity Number' — ignore this field\n"
        "2. 'Entity Name' — type the entity name here\n\n"
        "Below the Entity Name field are two radio buttons:\n"
        "- 'Starts With' (default)\n"
        "- 'Contains'\n"
        "Select 'Contains' for broader matching, then click the Search button.\n\n"
        "SIDEBAR NOTE: The left sidebar has links to search by Officials, Agents, "
        "etc. Ignore these — use the main Entity Name search.\n\n"
        "RESULTS: A table appears with entity names, numbers, and status. "
        "Click the entity name link for the closest match.\n\n"
        "DETAIL PAGE: The detail page shows:\n"
        "- Entity name, type, status, and formation date at the top\n"
        "- Registered Agent: name and address in a labeled section\n"
        "- OFFICERS: Look for an 'Officials' section. Alaska lists officers "
        "by Name, Title, and Address. This is typically on the same detail page. "
        "Scroll down to find all officials listed."
    ),

    # ─── ARIZONA ───────────────────────────────────────────────
    "AZ": (
        "The Arizona Corporation Commission business search is at "
        "arizonabusinesscenter.azcc.gov/businesssearch. The page loads with "
        "multiple search filter options.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "The page has several search fields. Decide whether the entity provided "
        "is a business name or a person/agent name.\n"
        "- If it is a business name (most likely): use the 'Business Name' search box\n"
        "- If it is a person/agent name: look for an agent name search option\n\n"

        "═══ BUSINESS NAME SEARCH ═══\n"
        "1. Type the entity name into the 'Business Name' search box\n"
        "2. Select the 'Contains' radio button — this gives the broadest match "
        "and the highest likelihood of finding the entity\n"
        "3. Click the 'Business Search' button in the bottom right of the screen\n\n"

        "═══ CAPTCHA ═══\n"
        "After clicking search, a CAPTCHA will likely appear. It shows a set of "
        "letters and numbers as an image. Read the characters from the image and "
        "type them into the text input box to solve it. Submit the CAPTCHA to "
        "proceed.\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "Results populate below the search filters section. Each result shows "
        "the business name as a clickable hyperlink. Click the business name "
        "hyperlink that most closely matches the entity you were given to search.\n\n"

        "═══ BUSINESS INFORMATION PAGE — EXTRACT EVERYTHING ═══\n"
        "The detail page shows all entity information in sections from top to bottom:\n\n"
        "TOP SECTION — Entity Details:\n"
        "- Formation Date\n"
        "- Principal Office Address — this is the BUSINESS address, record it\n"
        "- Entity Status (Active/Inactive/etc.)\n\n"
        "STATUTORY AGENT SECTION (2 sections below the top):\n"
        "- Agent Name — record this\n"
        "- Agent Type — 'Corporation' or 'Individual'. If the agent is NOT an "
        "individual (i.e. it is a corporation), record the agent type in "
        "parentheses alongside the name, e.g. 'CT Corporation System (Corp)'\n"
        "- Statutory Agent Address — record the full address\n\n"
        "PRINCIPAL INFORMATION (OFFICERS) SECTION:\n"
        "- This section lists all officers/principals of the entity\n"
        "- For EACH officer, extract:\n"
        "  * Name\n"
        "  * Address (full street address, city, state, zip)\n"
        "  * Date took office — NOT relevant, do not record this\n"
        "- Record every officer listed in this section"
    ),

    # ─── ARKANSAS ──────────────────────────────────────────────
    "AR": (
        "The Arkansas SOS search redirects to sos-corp-search.ark.org/corps. "
        "The page shows 'Search Incorporations, Cooperatives, Banks and Insurance "
        "Companies' at the top.\n\n"
        "SEARCH FORM (top to bottom):\n"
        "1. 'Corporation Type' dropdown — leave on 'All Types'\n"
        "2. 'Name' text field — type the entity name here (this is the primary search)\n"
        "3. 'Fictitious Name' — ignore\n"
        "4. 'Registered Agent (RA)' — ignore\n"
        "5. 'RA City' — ignore\n"
        "6. 'RA State' dropdown — ignore (leave on 'Any State')\n"
        "7. 'Filing #' — ignore\n"
        "Click the 'Search' button below the form.\n\n"
        "RESULTS: Matching entities appear in a list below the form. "
        "Click the entity name that most closely matches.\n\n"
        "DETAIL PAGE: Shows entity details including:\n"
        "- Filing number, entity name, type, status, formation date\n"
        "- Registered Agent name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Look for 'Officers', 'Directors', or 'Principals' section. "
        "Arkansas lists officers on the detail page — scroll down past the "
        "registered agent info. Each officer has Name, Title, and Address."
    ),

    # ─── CALIFORNIA ────────────────────────────────────────────
    "CA": (
        "The California bizfile portal at bizfileonline.sos.ca.gov/search/business "
        "has bot protection that may show a 'Please stand by' interstitial. Wait for "
        "it to resolve — the page will load automatically after a few seconds.\n\n"
        "Once the page loads, scroll down to the BOTTOM of the page. At the very "
        "bottom you will find a search box — this is the main entity search input. "
        "The search box has a filter that defaults to 'Contains (Keywords)' which "
        "is correct — do NOT change it or use the Advanced Search option.\n\n"
        "Type the entity name into the search box and click Search or press Enter.\n\n"
        "RESULTS: Matching entities appear below the search box. Scroll down slightly "
        "to see them. Each result shows the entity name in a blue clickable box, "
        "along with entity number and status. Click the blue box containing the "
        "entity name that best matches your search.\n\n"

        "═══ PHASE 1: DETAIL PANEL ═══\n"
        "After clicking an entity name, a detail panel slides in from the RIGHT "
        "side of the screen. Extract ALL of the following from this panel:\n"
        "- Entity status, standing, formed-in state, entity type\n"
        "- Principal Address (street, city, state, zip) — this is the business address\n"
        "- Mailing Address (if different from principal)\n"
        "- Agent for Service of Process: name and address\n"
        "- If any officers, members, managers, or directors are listed here, "
        "record each one with their name, title, and full address\n\n"
        "IMPORTANT: The 'CA Registered Corporate Agent Authorized Employee(s)' "
        "section lists employees of the registered agent company (e.g. Cogency "
        "Global, CT Corporation). These are NOT officers of the entity — do NOT "
        "record them as officers. They all share the same agent office address.\n\n"

        "═══ PHASE 2: FILING HISTORY — THIS IS CRITICAL ═══\n"
        "At the bottom of the detail panel are two buttons:\n"
        "- 'View History' — CLICK THIS BUTTON\n"
        "- 'Request Access' — IGNORE this\n\n"
        "The filing history page shows all documents as expandable rows, ordered "
        "most recent (top) to oldest (bottom). Each row shows filing type and date.\n\n"

        "STEP A — Download and read ALL filing documents in the history:\n"
        "- Go through EVERY filing in the list — SI filings, Articles of "
        "Organization/Incorporation, Amendments, everything\n"
        "- For each filing: click to expand the row, then click the PDF link to "
        "download/open the document\n"
        "- Read each document fully and extract any useful information\n\n"
        "What to look for in each document type:\n\n"
        "STATEMENT OF INFORMATION (SI) filings (labeled 'SI-COMPLETE', "
        "'SI-NO CHANGE', 'Statement of Information' — form LLC-12 for LLCs, "
        "SI-550 for Corps):\n"
        "  * Section 5 (LLCs): Manager(s) or Member(s) — full name AND full address\n"
        "    Example: 'Dawood Beshay, 41760 Ivy Street Suite 201, Murrieta CA 92562'\n"
        "  * Section 7: Type of Business description\n"
        "  * Section 8 (LLCs): Chief Executive Officer name and address (if any)\n"
        "  * For Corporations: CEO, CFO, Secretary, and all Directors with addresses\n"
        "  * The signature line confirms the signer's name and title\n\n"
        "ARTICLES OF ORGANIZATION / INCORPORATION:\n"
        "  * Organizer/Incorporator name and address\n"
        "  * Initial agent for service of process\n"
        "  * Initial principal address\n\n"
        "AMENDMENTS / OTHER FILINGS:\n"
        "  * Name changes, address changes, agent changes\n"
        "  * Any additional officer or member information\n\n"
        "- Extract EVERY person found across ALL documents with their name, "
        "title/role, and complete address\n"
        "- If the same person appears in multiple filings, use the most recent "
        "information (latest address, latest title)\n\n"

        "PRIORITY: Many CA entities show ZERO officers on the detail panel — the "
        "filing documents are the ONLY place to find the actual managers/members "
        "and their addresses. You MUST download and read ALL of them.\n\n"
        "If no filings contain officer/member data, use whatever agent data was "
        "found on the detail panel."
    ),

    # ─── COLORADO ──────────────────────────────────────────────
    "CO": (
        "The Colorado SOS search is at sos.state.co.us/biz/BusinessEntityCriteriaExt.do. "
        "The page loads with a search box at the top and several hyperlinks below it.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Decide whether the record provided is an entity name or a person's name:\n"
        "- ENTITY NAME (most likely): Use the search box on the initial page\n"
        "- PERSON NAME: Click the 'Advanced Search' hyperlink below the search box "
        "(see Person Name Search section below)\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Enter the entity name into the search box at the top of the page\n"
        "2. Click the 'Search' button in the bottom left of the screen\n\n"
        "RESULTS: A new page loads showing all document filings for entities that "
        "match or are similar to the name entered. There may be multiple filing "
        "types for the same entity.\n"
        "- If there are multiple filing types, select the 'Articles of Organization' "
        "event (this is the primary formation document)\n"
        "- Click the ID Number hyperlink associated with that event\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The detail page shows entity information in sections:\n\n"
        "ENTITY INFO:\n"
        "- Entity Status (Good Standing, Delinquent, etc.)\n"
        "- Formation Date\n"
        "- Principal Office Street Address — this is likely a BUSINESS address, "
        "record it\n\n"
        "REGISTERED AGENT SECTION (below entity info):\n"
        "- Agent Name — record this\n"
        "- Agent Street Address — record this\n"
        "- Agent Mailing Address — record this if different from street address\n\n"
        "NOTE: Colorado does NOT list officers/principals on this page. The only "
        "person data available is the Registered Agent. Collect the agent info "
        "and finish.\n\n"

        "═══ PERSON NAME SEARCH (Advanced Search) ═══\n"
        "If the record provided is a person's name rather than an entity:\n"
        "1. From the initial page, click the 'Advanced Search' hyperlink below "
        "the search box\n"
        "2. A new page loads with multiple input fields and radio buttons\n"
        "3. Select the radio button next to 'Registered Agent'\n"
        "4. Separate the person's name into First, Last, and Middle Initial, "
        "then input each into their respective fields\n"
        "5. A CAPTCHA box appears at the bottom — this is an identify-and-select "
        "image CAPTCHA. Solve it by selecting the correct images.\n"
        "6. Click the 'Search' button\n\n"
        "RESULTS: A list of entities that have this person as their registered "
        "agent will appear. Select the entity that matches and proceed to the "
        "detail page as described above."
    ),

    # ─── CONNECTICUT ───────────────────────────────────────────
    "CT": (
        "The Connecticut search is at service.ct.gov/business — this is a "
        "Salesforce-based portal. The page may take a moment to load.\n\n"
        "SEARCH: Look for a search bar or 'Business Search' input field. "
        "The interface uses a step-based wizard with tabs. You want the "
        "'Business Name Search' option. Enter the entity name and submit.\n\n"
        "RESULTS: Results appear in a list or card format showing entity name, "
        "type, and status. Click the matching entity.\n\n"
        "DETAIL PAGE: Shows entity details including:\n"
        "- Business Name, Business ID, Entity Type, Status\n"
        "- Date of Incorporation/Formation\n"
        "- Registered Agent/Statutory Agent name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Connecticut typically lists officers on the detail page. "
        "Look for 'Officers', 'Directors', or 'Managers' section. Scroll down "
        "through the full detail page. Officers include Name, Title, and Address."
    ),

    # ─── DELAWARE ──────────────────────────────────────────────
    "DE": (
        "The Delaware Division of Corporations search at icis.corp.delaware.gov "
        "may block non-browser requests. With a real browser it should load.\n\n"
        "SEARCH: The page has a search form with:\n"
        "- 'Entity Name' text input — type the entity name\n"
        "- 'File Number' text input — ignore this\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table shows matching entities with Name, File Number, "
        "Incorporation Date, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Delaware's detail page shows:\n"
        "- Entity Name, File Number, Status (Good Standing/Void/etc.)\n"
        "- Incorporation Date, Entity Type\n"
        "- Registered Agent: name and address\n"
        "- IMPORTANT: Delaware does NOT publicly list officers/directors on "
        "their SOS portal. The only person you can get is the Registered Agent. "
        "Officer information is only available via paid certified copy. Record "
        "the Registered Agent and note that Delaware does not disclose officers online."
    ),

    # ─── FLORIDA ───────────────────────────────────────────────
    "FL": (
        "The Florida Sunbiz portal is at search.sunbiz.org/Inquiry/"
        "CorporationSearch/ByName. The page loads with a search bar and several "
        "hyperlinks below it. It may have bot protection — wait for the page to "
        "fully load.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Only two hyperlinks matter:\n"
        "- 'Entity Name' — use this for company/LLC/Corp searches\n"
        "- 'Officer/Registered Agent Name' — use this for person-name searches\n\n"
        "DECISION: Decide whether the record provided is an entity name or a "
        "person/agent name BEFORE searching.\n"
        "- If it is a business name (most likely): click the 'Entity Name' hyperlink\n"
        "- If it is a person's name: click the 'Officer/Registered Agent Name' "
        "hyperlink\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. After clicking 'Entity Name', type the entity name into the search "
        "bar at the top of the page\n"
        "2. Click the 'Search Now' button\n\n"
        "RESULTS: A new page loads showing a list of entities that match the "
        "name to some degree. Each result shows Document Number, Entity Name, "
        "and Status. The entity names are clickable hyperlinks.\n"
        "- Select the entity that is an EXACT match to the record given, or the "
        "CLOSEST possible match if no exact match exists\n"
        "- Click the hyperlinked entity name to open the detail page\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The detail page contains all the business information. Extract ALL of "
        "the following, going top to bottom:\n\n"
        "ENTITY INFO:\n"
        "- Date Filed — this is the INCEPTION DATE of the entity, record it as "
        "the formation date\n"
        "- Status (Active, Inactive, Dissolved, etc.) — record this\n\n"
        "PRINCIPAL ADDRESS SECTION:\n"
        "- This is the business address, tag it as such and record it\n\n"
        "REGISTERED AGENT NAME & ADDRESS SECTION:\n"
        "- Registered Agent Name — record this\n"
        "- Address associated with the registered agent — record this\n\n"
        "OFFICER/DIRECTOR DETAIL SECTION:\n"
        "- This section lists every officer/director associated with the filing\n"
        "- For EACH officer, extract:\n"
        "  * Title (President, Vice President, Director, Manager, etc.)\n"
        "  * Name\n"
        "  * Address\n"
        "- All officers are on the same page — just scroll down past the "
        "registered agent section. No tabs to click."
    ),

    # ─── GEORGIA ───────────────────────────────────────────────
    "GA": (
        "The Georgia SOS search is at ecorp.sos.ga.gov/BusinessSearch. The page "
        "loads with FOUR search input boxes:\n"
        "1. Business Name\n"
        "2. Control Number — IGNORE this, never use it\n"
        "3. Registered Agent Name\n"
        "4. Officer Name\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Before searching, decide whether the record is an entity name or a "
        "person's name.\n"
        "- If it is a business name (most likely): use the Business Name flow below\n"
        "- If it is a person's name: use the Person Name flow at the bottom of "
        "these instructions\n\n"

        "═══ BUSINESS NAME SEARCH ═══\n"
        "1. Select the radio button next to 'Business Name'\n"
        "2. Select the radio button at the top labeled 'Contains' — this gives "
        "the broadest match and the highest hit rate\n"
        "3. Input the entity name into the Business Name box\n"
        "4. Click 'Search'\n\n"
        "RESULTS: A new page loads with all records that could match the entity. "
        "Select the EXACT match if available, or the CLOSEST match. Click the "
        "blue hyperlinked entity name to open the detail page.\n\n"

        "═══ DETAIL PAGE — INITIAL EXTRACTION ═══\n"
        "The detail page shows general entity info. Extract:\n"
        "- Status of the entity (top of page)\n"
        "- Principal Office Address (top of page) — this is the BUSINESS address, "
        "tag and record it\n"
        "- Registered Agent Name (section below) — record this\n"
        "- Registered Agent Address (section below) — record this and tag it as "
        "the agent address\n\n"

        "═══ FILING HISTORY — CRITICAL FOR OFFICER DATA ═══\n"
        "Officer/Manager data is NOT on the detail page. You MUST proceed to the "
        "filing history.\n\n"
        "At the very bottom of the detail page there are 3 buttons:\n"
        "- 'Filing History' — CLICK THIS BUTTON\n"
        "- 'Name History' — IGNORE\n"
        "- 'Return to Business Search' — IGNORE\n\n"
        "FILING HISTORY PAGE: A new page loads with tabular records of all filings. "
        "It shows:\n"
        "- Initial formation document(s) — Articles of Organization, Articles of "
        "Incorporation, or Application for Certificate of Authority (for foreign "
        "entities)\n"
        "- Annual Registration documents\n\n"
        "STEP — Download the INITIAL FILING document:\n"
        "1. Click the hyperlink for the initial formation document FIRST\n"
        "2. Open/download the PDF\n"
        "3. The PDF contains all the previously gathered info PLUS the most "
        "important data: the MANAGER(S) section\n\n"
        "MANAGER(S) SECTION IN THE PDF — THIS IS IMPERATIVE:\n"
        "The PDF includes a 'MANAGER(S)' section (also referred to as Officers) "
        "with the following columns:\n"
        "  * NAME\n"
        "  * TITLE (Manager, CEO, etc.)\n"
        "  * ADDRESS — this is a HOME/RESIDENTIAL address\n"
        "Example: 'Argus Wiley | MANAGER | 233 N. Main Street, Suite 7, "
        "Greenville, SC, 29601, USA'\n\n"
        "You MUST collect every manager listed with their name, title, and "
        "complete address. The home address is the most valuable piece of data "
        "from this filing — do not skip it. Also check the AUTHORIZER INFORMATION "
        "section at the bottom for the signer's name and title.\n\n"
        "Only after extracting all manager data from the PDF can the agent "
        "consider the job successful.\n\n"

        "═══ PERSON NAME SEARCH (Two-Stage Reasoning Loop) ═══\n"
        "If the record is a person's name, do NOT use the Business Name box.\n\n"
        "STAGE 1 — Registered Agent search:\n"
        "1. Input the person's name into the 'Registered Agent Name' box\n"
        "2. Select the radio button next to 'Registered Agent Name'\n"
        "3. Click 'Search'\n"
        "4. If results appear, select the entity that BOTH matches the registered "
        "agent name closely AND makes sense in the context of the source list. "
        "Example: for a Del Taco FDD, an entity named 'ATL Tacos' is a likely "
        "candidate over an unrelated business. Then proceed with the normal "
        "detail page + filing history extraction flow above.\n\n"
        "STAGE 2 — Officer search (only if Stage 1 returned NO results):\n"
        "1. Go back to the search page\n"
        "2. Switch the search filter from 'Registered Agent Name' to 'Officer Name'\n"
        "3. Input the same person's name into the Officer Name box\n"
        "4. Select the radio button next to 'Officer Name'\n"
        "5. Click 'Search'\n"
        "6. Proceed in the same manner — pick the most contextually appropriate "
        "match and run the normal extraction flow."
    ),

    # ─── HAWAII ────────────────────────────────────────────────
    "HI": (
        "The Hawaii Business Express (HBE) portal at hbe.ehawaii.gov may redirect "
        "to a login page. If you see a login page, look for a 'Search' or "
        "'Public Search' link that does NOT require login.\n\n"
        "SEARCH: The page has a search box with a dropdown to the RIGHT of it. "
        "Change the dropdown from 'Begins with' to 'Contains' for broader matching. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table appears with business names as blue clickable links, "
        "plus filing info columns. Click the matching business name.\n\n"
        "DETAIL PAGE: The detail page has a 'General Info' section showing:\n"
        "- Entity status, standing, contact information\n"
        "- Registered Agent: name and address — on the main page\n"
        "- OFFICERS: Listed on the main detail page with all addresses. "
        "Trade names, trademarks, and service marks also shown.\n"
        "All officer data is on ONE page — no tabs needed.\n\n"
        "NOTE: Hawaii uses DCCA (Dept of Commerce & Consumer Affairs), not "
        "'Secretary of State'."
    ),

    # ─── IDAHO ─────────────────────────────────────────────────
    "ID": (
        "The Idaho SOS search is at sosbiz.idaho.gov/search/business. The page "
        "loads with a sidebar and a top menu — IGNORE both of these. The only "
        "element that matters is the search input box in the CENTER of the page, "
        "with an 'Advanced Search Options' button below it.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Decide whether the record provided is an entity name or an agent/person "
        "name BEFORE searching.\n"
        "- If it is a business name (most likely): use the Entity Search flow below\n"
        "- If it is a person's name: search by agent name through the same flow "
        "but with the appropriate filter\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Click 'Advanced Search Options' to expand the dropdown\n"
        "2. Select the 'Contains' radio button — this gives the broadest search "
        "range and the highest hit rate\n"
        "3. Type the entity name into the input box in the center of the page\n"
        "4. Click the 'Search' button in the center of the screen\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "A tabular view of results appears below the search box, showing all "
        "entities similar to the name searched. Each result is shown as a blue "
        "clickable box.\n"
        "- Click the blue box for the entity that is a DIRECT match to the "
        "record provided, OR the blue box for the closest match if no exact "
        "match exists\n\n"

        "═══ DETAIL SIDE PANEL ═══\n"
        "After clicking a result, a side panel appears on the RIGHT side of the "
        "screen with general entity information. Extract:\n"
        "- Entity Status\n"
        "- Initial Filing Date — this is the entity's INCEPTION/FORMATION date, "
        "record it as such\n"
        "- Any other top-level details visible on the panel\n\n"
        "Below all the presented details on the side panel is a 'View History' "
        "button. CLICK THIS BUTTON.\n\n"

        "═══ FILING HISTORY POPUP ═══\n"
        "A large popup appears showing the entity's filing history.\n\n"
        "STEP 1 — Download the MOST RECENT Annual Report:\n"
        "1. Click the 'Expand All' button to expand all filing entries\n"
        "2. Find the most recent annual report\n"
        "3. Click 'Download' to download the PDF\n"
        "4. Open the document and extract the following:\n\n"
        "   REGISTERED AGENT:\n"
        "   - Name and physical address — record both\n\n"
        "   MANAGERS / MEMBERS (OFFICERS) TABLE:\n"
        "   - The PDF contains a tabular section listing all managers and members\n"
        "   - For EACH person, extract: Name, Title, Address\n"
        "   - The address listed here is a BUSINESS address — tag it as such\n"
        "   - Collect EVERY person in the table\n\n"

        "STEP 2 — Download the INITIAL FILING document:\n"
        "1. Scroll to the BOTTOM of the business filing history section\n"
        "2. Find the initial filing document (Articles of Organization/Incorporation)\n"
        "3. Click 'Download' to download the PDF\n"
        "4. Open the document\n\n"
        "   DISCREPANCY CHECK — CRITICAL:\n"
        "   - Identify any people on the initial filing who ALSO appeared on the "
        "most recent annual report\n"
        "   - Compare their addresses across the two documents\n"
        "   - If a person's address differs between filings (e.g. Mark J Miller "
        "had one address on the initial filing and a different address on the "
        "annual report), this is a DISCREPANCY worth recording\n"
        "   - Add ALL discovered addresses for that person to their record as a "
        "comma-separated list, e.g.:\n"
        "     '123 Main St, Boise, ID - 125 Main St, Boise, ID'\n"
        "   - This historical address data will be used downstream by a skip "
        "tracing API to locate the person, so capturing every variant is "
        "essential — do not discard old addresses\n\n"
        "Only after collecting BOTH the most recent annual report data AND the "
        "discrepancy data from the initial filing can the agent consider the job "
        "successful."
    ),

    # ─── ILLINOIS ──────────────────────────────────────────────
    "IL": (
        "The Illinois SOS business search is at apps.ilsos.gov/businessentitysearch/. "
        "The page loads with a search input bar in the center and several radio "
        "buttons for narrowing search parameters.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Before entering anything, decide whether the record is a business entity "
        "name or a person's name.\n"
        "- If it is a business name (most likely): select the 'Business Name' "
        "radio button\n"
        "- If it is a person's name: select the appropriate radio button for "
        "officer/agent search\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Select the radio button next to 'Business Name'\n"
        "2. Input the entity name into the search box\n"
        "3. Click 'Submit'\n\n"

        "═══ CAPTCHA HANDLING ═══\n"
        "After clicking Submit, a CAPTCHA will likely appear:\n"
        "1. Click the 'I am not a robot' checkbox\n"
        "2. You will then be prompted to select image tiles — either tiles that "
        "contain part of an object (e.g. crosswalks, traffic lights) or individual "
        "images containing a specific object\n"
        "3. Select the correct tiles/images\n"
        "4. Click the 'Verify' button\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "After verification, a tabular view of matching entities appears.\n"
        "- Select the entity name that is an EXACT match to the record\n"
        "- If no exact match, select the CLOSEST match\n"
        "- Click the entity name\n\n"

        "═══ DETAIL PAGE — GENERAL INFORMATION ═══\n"
        "The page reloads with entity details in the center section. Collect:\n"
        "- Entity Status\n"
        "- Registered Agent Name\n"
        "- Registered Agent Address, City, State, Zip\n\n"

        "═══ MANAGERS TAB — CRITICAL ═══\n"
        "Scroll down slightly to find a tab-based navigation bar. Click the tab "
        "labeled 'Managers' (for LLCs) or 'Officers' (for Corporations).\n\n"
        "A tabular view of all managers/officers appears. For EACH manager:\n"
        "- Collect their Name and Address\n"
        "- It is IMPERATIVE that every manager is collected\n\n"

        "═══ CRITICAL: NAME FORMAT ═══\n"
        "When a registered manager is an individual (not an entity), Illinois "
        "displays names in REVERSE ORDER: 'Last, First'.\n"
        "You MUST reorganize these to standard order: 'First Last' when recording "
        "them on the XLSX. For example:\n"
        "- 'Smith, John' → 'John Smith'\n"
        "- 'Rodriguez, Maria' → 'Maria Rodriguez'\n\n"
        "Once all general info, registered agent, and manager data has been "
        "collected (with names in correct order), the agent can consider the "
        "job successful."
    ),

    # ─── INDIANA ───────────────────────────────────────────────
    "IN": (
        "The Indiana business search is at bsd.sos.in.gov/publicbusinesssearch. "
        "The page loads with a search section at the top containing several radio "
        "buttons with corresponding text labels, and a reCAPTCHA box in the top "
        "right corner.\n\n"

        "═══ CAPTCHA — MUST BE COMPLETED FIRST ═══\n"
        "Before doing ANYTHING else, complete the reCAPTCHA:\n"
        "1. Click the 'I am not a robot' checkbox in the top right\n"
        "2. Select the image tiles as prompted (crosswalks, traffic lights, etc.)\n"
        "3. Click the 'Verify' button\n"
        "The search will NOT work until the CAPTCHA is completed.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "After completing the CAPTCHA, decide whether the record is a business "
        "entity name or a person's name.\n\n"
        "IF BUSINESS ENTITY (most likely):\n"
        "1. Select the radio button next to 'Business Name'\n"
        "2. Enter the entity name into the input box below the radio button\n"
        "3. Click the 'Search' button at the very bottom of the page\n\n"
        "IF PERSON NAME:\n"
        "1. Select the radio button next to 'Incorporator or governing person'\n"
        "2. Enter the person's name into the input box below\n"
        "3. Click the 'Search' button at the very bottom of the page\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "The page reloads (wait for it to fully load). A tabular view of all "
        "matching records appears.\n"
        "- Identify the business name that is an EXACT match to the record\n"
        "- If no exact match, select the closest and most likely match\n"
        "- Click the hyperlinked Business ID of the matching record\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "A new page loads with entity details. Extract in this order:\n\n"
        "GENERAL DETAILS (top of page):\n"
        "- Entity Status — COLLECT this\n"
        "- Principal Office Address — this is the BUSINESS address, COLLECT this\n\n"
        "GOVERNING AUTHORITIES TABLE (below general details):\n"
        "- This table lists the members/officers of the entity\n"
        "- For EACH individual listed, collect:\n"
        "  * Full Name\n"
        "  * Address\n"
        "- Every governing authority MUST be collected\n\n"
        "REGISTERED AGENT SECTION (below the governing authorities table):\n"
        "- Registered Agent Name — COLLECT this\n"
        "- Registered Agent Address, City, State, Zip — COLLECT all of this\n\n"
        "Once entity status, principal address, all governing authorities, and "
        "registered agent data have been collected, the agent can consider the "
        "job complete."
    ),

    # ─── IOWA ──────────────────────────────────────────────────
    "IA": (
        "The Iowa SOS business search is at sos.iowa.gov/search/business/"
        "search.aspx. The page loads with a search box in the center.\n\n"

        "═══ SEARCH ═══\n"
        "1. Enter the entity name into the search box\n"
        "2. Click the 'Search' button below it\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "The page reloads with a list of all matching records.\n"
        "- Identify the entity name that is an EXACT match to the given record\n"
        "- Click the hyperlinked 'Business No.' to the RIGHT of the matching "
        "entity name\n\n"

        "═══ DETAIL PAGE — TABBED INTERFACE ═══\n"
        "The detail page has several tabs at the top. You MUST visit multiple "
        "tabs to collect all data:\n\n"

        "TAB 1 — 'Agent' tab (click this FIRST):\n"
        "- Full Name of the registered agent\n"
        "- Address, City, State, Zip of the registered agent\n"
        "- ALL of this information MUST be gathered and recorded\n\n"

        "TAB 2 — 'Address' tab (to the LEFT of the Agent tab):\n"
        "- Business Address, City, State, Zip\n"
        "- Record this as the business/principal address on the XLSX\n\n"

        "TAB 3 — 'Officers' tab (CRITICAL):\n"
        "- This tab lists all officers/directors of the entity\n"
        "- For EACH officer, collect:\n"
        "  * Name\n"
        "  * Address, City, State, Zip\n"
        "- It is IMPERATIVE that every officer is collected with their "
        "complete address information\n\n"
        "Once all three tabs have been visited and all agent, address, and "
        "officer data has been collected, the agent can consider the job "
        "successful."
    ),

    # ─── KANSAS ────────────────────────────────────────────────
    "KS": (
        "The Kansas SOS business entity search is at "
        "sos.ks.gov/eforms/BusinessEntity/Search.aspx.\n\n"
        "SEARCH: The page has a text input for 'Business Entity Name'. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities with Name, Type, Status, "
        "and Filing Date. Click the entity name.\n\n"
        "DETAIL PAGE: Kansas shows:\n"
        "- Entity Name, Type, Status, Formation Date\n"
        "- Registered Agent: name, address (under 'Resident Agent')\n"
        "- Principal Office address\n"
        "- OFFICERS: Kansas lists officers/directors in a section below the "
        "entity summary. Each entry has Name, Title, and Address. "
        "Scroll down on the detail page to find officers."
    ),

    # ─── KENTUCKY ──────────────────────────────────────────────
    "KY": (
        "The Kentucky SOS business entity search is at "
        "sosbes.sos.ky.gov/BusSearchNProfile/search.aspx.\n\n"
        "SEARCH: The page has:\n"
        "- A dropdown to select search type: 'Business Name or Organization Number', "
        "'City Name of principal office', or 'Zip Codes'\n"
        "- Leave on 'Business Name or Organization Number'\n"
        "- A text input field — type the entity name\n"
        "- A checkbox 'Show active entities only' — leave it CHECKED for initial "
        "search (uncheck if no results)\n"
        "- An 'Advanced Search' link for more options — typically not needed\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table of matching entities. Click the entity name link.\n\n"
        "DETAIL PAGE: Kentucky shows:\n"
        "- Entity Name, Organization Number, Type, Status\n"
        "- Filing Date, Standing (Good Standing/Not Good Standing)\n"
        "- Registered Agent: name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Look for 'Current Representatives' or 'Officers' section. "
        "Kentucky lists each officer with Name, Title, and Address. This may "
        "be on the main detail page — scroll down to find it."
    ),

    # ─── LOUISIANA ─────────────────────────────────────────────
    "LA": (
        "The Louisiana SOS search at "
        "coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx shows "
        "'Search for Louisiana Business Filings'.\n\n"
        "SEARCH: The page offers three search methods:\n"
        "1. 'Entity Name Search' — type the full entity name here (primary method)\n"
        "2. 'Charter/Registration Number Search' — ignore\n"
        "3. 'Officer/Agent Name Search' — use for PERSON searches (has first/last fields)\n\n"
        "IMPORTANT: There is a CHECKBOX for human verification that MUST be "
        "checked BEFORE clicking Search. It may be a simple checkbox or a "
        "reCAPTCHA widget. Check it, then click 'Search'.\n\n"
        "RESULTS: A table shows matching entities with business name, entity type, "
        "city, status, and a 'Details' button. Click the 'Details' button on the "
        "matching row.\n\n"
        "DETAIL PAGE: Louisiana shows everything on ONE page:\n"
        "- Charter Number, Entity Name, Type, Status\n"
        "- Formation/Incorporation Date\n"
        "- Registered Agent: name AND full address\n"
        "- Registered Office location\n"
        "- OFFICERS: Louisiana lists officers, directors, members, AND managers "
        "in separate categories — check ALL of them. Names with titles and "
        "addresses are on the main detail page. No tabs needed.\n"
        "- Filing history at the bottom."
    ),

    # ─── MAINE ─────────────────────────────────────────────────
    "ME": (
        "The Maine ICRS (Interactive Corporate Records System) at "
        "icrs.informe.org may also be at apps3.web.maine.gov — both host "
        "the same system.\n\n"
        "SEARCH: The page has two search fields:\n"
        "- 'Keyword from name to be searched' — type the entity name here "
        "(searches legal name, former names, assumed names, and fictitious "
        "names simultaneously)\n"
        "- 'Charter number' — ignore this\n"
        "Click the search button.\n\n"
        "RESULTS: A table with Charter Number, Legal Name, Entity Type, "
        "Filing Type, and Status. Click the entity name or charter number.\n\n"
        "DETAIL PAGE: Maine shows on ONE page:\n"
        "- Charter Number, Legal Name, Entity Type, Status\n"
        "- Formation Date\n"
        "- IMPORTANT: Maine uses 'Clerk' instead of 'Registered Agent' for "
        "domestic corporations. Foreign entities use 'Registered Agent'. "
        "Look for BOTH terms — name and address are on the main page.\n"
        "- Principal/home office address\n"
        "- OFFICERS: Officers and directors are on the main detail page. "
        "Each has Name, Title, and Address.\n"
        "- Filing history and document images at the bottom."
    ),

    # ─── MARYLAND ──────────────────────────────────────────────
    "MD": (
        "The Maryland Business Express portal at "
        "egov.maryland.gov/BusinessExpress/EntitySearch has the search interface.\n\n"
        "SEARCH: The page shows three search options with radio buttons:\n"
        "- 'Business Name' (default — use this)\n"
        "- 'Department ID'\n"
        "- 'Employer Identification Number (EIN)'\n"
        "Select 'Business Name', type the entity name in the text field, "
        "and click the Search button.\n\n"
        "RESULTS: Matching entities appear below. Click the entity name "
        "that most closely matches.\n\n"
        "DETAIL PAGE: Maryland shows:\n"
        "- Entity Name, Department ID, Status (Active/Forfeited/etc.)\n"
        "- Date of Formation, Entity Type\n"
        "- Resident Agent: name and address (Maryland uses 'Resident Agent' "
        "instead of 'Registered Agent')\n"
        "- Principal Office address\n"
        "- OFFICERS: Maryland may list officers or direct you to view "
        "annual report filings. Look for 'Officers' or 'Principal Members' "
        "section. If not visible, check filing documents for officer data."
    ),

    # ─── MASSACHUSETTS ─────────────────────────────────────────
    "MA": (
        "The Massachusetts Corporations Search at "
        "corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx has "
        "multiple search options.\n\n"
        "SEARCH: The page shows four radio buttons at top:\n"
        "- 'Entity Name' (default — use this for business searches)\n"
        "- 'Individual Name' (use for person name searches)\n"
        "- 'Identification Number'\n"
        "- 'Filing Number'\n\n"
        "For ENTITY searches:\n"
        "- Select 'Entity Name'\n"
        "- Type the entity name in the 'Enter name:' text field\n"
        "- Search type dropdown: select 'Full text' for broadest matching "
        "(options: 'Begins with', 'Exact match', 'Full text', 'Soundex')\n"
        "- Click 'Search'\n\n"
        "For PERSON searches:\n"
        "- Select 'Individual Name'\n"
        "- Fill in First, Middle, Last name fields\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table of matching entities with Name, ID, Type, Status. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Massachusetts shows:\n"
        "- Entity Name, ID Number, Type, Status\n"
        "- Date of Organization\n"
        "- Registered Agent: name and address (may say 'Resident Agent')\n"
        "- Principal Office\n"
        "- OFFICERS: Massachusetts lists officers/directors in the detail view. "
        "Look for 'Officers' tab or section. Each officer has Name, Title, "
        "and Residential Address. Click any available tab to see officers."
    ),

    # ─── MICHIGAN ──────────────────────────────────────────────
    "MI": (
        "The Michigan LARA search is at mibusinessregistry.lara.state.mi.us/"
        "search/business.\n\n"

        "═══ LOGIN — REQUIRED BEFORE SEARCHING ═══\n"
        "Michigan requires a login to access business records.\n"
        "1. In the top right corner of the page, click the 'Login' button\n"
        "2. Enter the User ID from the MI_SOS_USER environment variable\n"
        "3. Enter the Password from the MI_SOS_PASS environment variable\n"
        "4. Check the box to agree to the terms and conditions\n"
        "5. Click 'Login'\n\n"
        "After login, you will see a page that says 'MiBusiness Registry Portal' "
        "with a 'Launch Service' button in the middle. Click 'Launch Service'.\n\n"
        "After a short loading screen, you will see a page with a sidebar on the "
        "left. Click the 'Search' section in the left sidebar.\n\n"

        "═══ SEARCH PAGE ═══\n"
        "The search page shows a search bar with a dropdown that opens the "
        "advanced search section.\n\n"
        "DECISION: Before typing anything, decide whether the record provided "
        "is an entity name or a person's name.\n"
        "- If it is a business name (most likely): use the Entity Name flow below\n"
        "- If it is a person's name: adapt the search accordingly\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Click the dropdown to open the advanced search section\n"
        "2. Select the radio button next to 'Contains' to cast a wider search net\n"
        "3. Type the entity name into the search bar above\n"
        "4. Click 'Search'\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "The page loads briefly and presents all potential matches.\n"
        "- Select the EXACT match for the entity, or the CLOSEST possible match "
        "if no exact match exists\n"
        "- Click to select the entity\n\n"

        "═══ DETAIL SIDEBAR — INITIAL DATA ═══\n"
        "A sidebar appears with entity information. Collect ALL of the following:\n"
        "- Entity Status\n"
        "- Registered Agent Name\n"
        "- Registered Agent Address\n"
        "- Initial Filing Date (the entity's formation/inception date)\n\n"
        "Then click the button that reads 'View History & Filings'.\n\n"

        "═══ FILING HISTORY POPUP — DOWNLOAD AND PARSE ALL ═══\n"
        "A popup window appears with the entity's filing history.\n\n"
        "STEP 1 — Articles of Organization:\n"
        "- Scroll to the BOTTOM of the filing list — the initial filing "
        "(Articles of Organization) is typically the last entry\n"
        "- Download this document\n"
        "- Open it and extract the names of ALL signatories (Organizers) and "
        "their addresses if listed\n"
        "- Record each signatory as an officer with title='Organizer'\n\n"

        "STEP 2 — Assumed Name filing (if it exists):\n"
        "- Look through the filings for a document called 'Assumed Name'\n"
        "- If found, download and open it\n"
        "- Extract the 'Proposed Assumed Name' — this is the potential DBA "
        "for the company. Record it as the DBA name.\n\n"

        "STEP 3 — ALL Annual Reports:\n"
        "- Download EVERY annual report listed in the filing history\n"
        "- Open each one and extract the officer/member information:\n"
        "  * Officer/Member Name\n"
        "  * Title\n"
        "  * Address\n"
        "- Do this for EVERY annual report, not just the most recent one\n\n"

        "═══ ADDRESS CONSOLIDATION — CRITICAL ═══\n"
        "After parsing all filings (articles, annual reports, assumed name):\n"
        "- For EACH individual officer/agent, compile a list of ALL addresses "
        "found across all documents\n"
        "- If a person's address differs between filings, capture ALL variants\n"
        "- Record the addresses as a hyphen-separated list in a single cell:\n"
        "  '123 Main St, Detroit, MI - 456 Oak Ave, Lansing, MI'\n"
        "- This historical address data is essential for downstream skip tracing. "
        "Do NOT discard older addresses — every variant must be preserved."
    ),

    # ─── MINNESOTA ─────────────────────────────────────────────
    "MN": (
        "The Minnesota SOS portal redirects to mblsportal.sos.mn.gov/Business/Search. "
        "Use this URL directly.\n\n"
        "SEARCH: Look for a 'Business Name' text input. Type the entity name "
        "and click 'Search'.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Minnesota shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date Filed, Home Jurisdiction\n"
        "- Registered Agent/Office: name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Minnesota may list officers on the detail page or in "
        "a separate 'Annual Report' section. Look for 'Principals', "
        "'Officers', or 'Managers' section and scroll down."
    ),

    # ─── MISSISSIPPI ───────────────────────────────────────────
    "MS": (
        "The Mississippi SOS search is at corp.sos.ms.gov/corp/portal/c/page/"
        "corpBusinessIdSearch/portal.aspx. The page loads with several interactive "
        "buttons.\n\n"

        "═══ SEARCH TABS ═══\n"
        "Under the 'Business Search' section there are 4 tabs:\n"
        "1. Business Name\n"
        "2. Business ID — IGNORE, never use this\n"
        "3. Officer Name\n"
        "4. Registered Agent Name\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Before selecting a tab, decide whether the record is an entity name or "
        "a person's name.\n"
        "- If it is a business name (most likely): select the 'Business Name' tab\n"
        "- If it is a person's name: select either 'Officer Name' or "
        "'Registered Agent Name' tab as appropriate\n\n"

        "═══ BUSINESS NAME SEARCH ═══\n"
        "1. Click the 'Business Name' tab\n"
        "2. The system shows several radio buttons for search parameters. "
        "The default is 'Starting with' — KEEP this default selected\n"
        "3. Input the business name into the 'Business Name' input box\n"
        "4. Click the 'Search' button next to the input box\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "If matches are found, they appear below the input box under the "
        "'Business Name Search Results' section as a tabular view.\n"
        "- Identify the EXACT match to the business name that was input\n"
        "- If no exact match, select the entity with the CLOSEST name correlation\n\n"
        "NO RESULTS FALLBACK: If no records are found with 'Starting with', "
        "cycle through the other radio button search criteria (Contains, Exact "
        "Match, etc.) and re-search with each parameter until results appear.\n\n"
        "Once a match is found, click the 'Details' button in the far right "
        "column of that row.\n\n"

        "═══ DETAIL SECTION — EXTRACT EVERYTHING ═══\n"
        "A detail section loads with entity information. Extract ALL of:\n"
        "- Entity Status\n"
        "- Formation Date\n"
        "- Registered Agent Name and Agent Address\n"
        "- If officers/directors/members are listed on this page, collect "
        "EVERY officer with their name, title, and address\n\n"

        "═══ FILING DOCUMENTS — DOWNLOAD AND COMPARE ═══\n"
        "After collecting the detail page data:\n\n"
        "STEP 1 — Download the INITIAL FORMATION document:\n"
        "- Look for the initial filing (Articles of Organization, Certificate "
        "of Formation, etc.)\n"
        "- Download and open it\n"
        "- Extract any officers/agents/organizers listed with their names and "
        "addresses\n"
        "- Compare addresses against what was found on the detail page\n"
        "- If any person's address differs between the detail page and this "
        "filing, record ALL address variants as a hyphen-separated list:\n"
        "  '123 Main St, Jackson, MS - 124 Main St, Jackson, MS'\n\n"

        "STEP 2 — Download the MOST RECENT annual report:\n"
        "- Find and download the most recent annual report filing\n"
        "- Extract officer/agent names and addresses\n"
        "- Again compare against previously found addresses and add any "
        "new address variants to the hyphen-separated list for that person\n\n"

        "═══ BLOCKED / SYSTEM ERROR HANDLING ═══\n"
        "If at any point during the search process the agent encounters:\n"
        "- System error messages\n"
        "- DataDome blockade or bot protection pages\n"
        "- Any window indicating the search cannot proceed\n\n"
        "Then the agent MUST:\n"
        "- Mark the entity status as 'BLOCKED'\n"
        "- Write in the XLSX notes field: 'Needs manual open corporate enrichment'\n"
        "- Do NOT retry endlessly — mark it and move on to the next entity."
    ),

    # ─── MISSOURI ──────────────────────────────────────────────
    "MO": (
        "The Missouri SOS search at bsd.sos.mo.gov/BusinessEntity/BESearch "
        "may block automated requests. Wait for the page to load.\n\n"
        "SEARCH: The page has:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- Search type options may include 'Starts With', 'Contains'\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, Charter Number, "
        "Type, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Missouri shows:\n"
        "- Entity Name, Charter Number, Type, Status\n"
        "- Formation Date, Purpose\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Missouri typically lists officers directly on the "
        "detail page. Look for 'Officers/Directors' section showing "
        "Name, Title, and Address. Scroll down past the registered agent info."
    ),

    # ─── MONTANA ───────────────────────────────────────────────
    "MT": (
        "The Montana SOS search at biz.sos.mt.gov/search may not respond "
        "to static fetches but should work in a real browser.\n\n"
        "SEARCH: Look for a text input for 'Business Name'. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Montana shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Montana lists officers on the detail page. Look for "
        "'Officers' or 'Principals' section with Name, Title, and Address."
    ),

    # ─── NEBRASKA ──────────────────────────────────────────────
    "NE": (
        "The Nebraska SOS Corporate and Business Search is at "
        "www.nebraska.gov/sos/corp/corpsearch.cgi.\n\n"
        "SEARCH: The form has radio buttons at top for search type:\n"
        "- 'Name Starts With' (default — safest choice)\n"
        "- 'Name Keyword Search' (more forgiving for partial matches)\n"
        "- 'Name Sounds Like'\n"
        "- 'Name Exact Match'\n"
        "Select a radio button, then type the entity name in the text field.\n\n"
        "CAPTCHA: A Google reCAPTCHA ('I'm not a robot' checkbox) appears "
        "below the search field. This is MANDATORY — complete it before "
        "clicking 'Perform Search'.\n\n"
        "RESULTS: A table showing 25 per page: Company Name, SOS Account Number, "
        "Business Type, Status. Click the company name or 'Details' link.\n\n"
        "DETAIL PAGE: Shows entity name, SOS Account Number, formation date, "
        "next filing due, status, entity type.\n"
        "- Registered Agent: name and address shown on the free detail page\n"
        "- OFFICERS: LIMITED — Nebraska's free online search primarily shows "
        "the registered agent. Full officer/director lists are in Annual Report "
        "documents which require a FEE. Extract the registered agent and note "
        "that full officers require paid document access.\n\n"
        "FALLBACK: If the CAPTCHA cannot be solved, use Google search: "
        "'\"entity name\" site:nebraska.gov secretary of state'."
    ),

    # ─── NEVADA ────────────────────────────────────────────────
    "NV": (
        "The Nevada SOS business search is at esos.nv.gov/EntitySearch/"
        "OnlineEntitySearch. The page loads with an advanced search parameter "
        "menu.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Decide whether the record provided is a business name or a person's name.\n"
        "- If it is a business name (most likely): use the Entity Name flow below\n"
        "- If it is a person's name: adapt the search accordingly using any "
        "officer/agent search options available\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Select the 'Contains' radio button at the top of the search menu — "
        "this gives the broadest match\n"
        "2. Input the entity name into the 'Name' search bar\n"
        "3. Click the 'Search' button at the bottom of the screen\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "After a short loading screen, a new page appears with a tabular view "
        "of all matching records.\n"
        "- Select the record that is an EXACT match to the search parameters\n"
        "- If no exact match, select the CLOSEST possible match\n"
        "- Click the hyperlinked entity name\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The detail page shows several sections of data. Extract ALL of:\n"
        "- Entity Status\n"
        "- Registered Agent Name and Address\n"
        "- ALL officers — each with Name, Title, and Address\n\n"

        "═══ FILING HISTORY — ADDRESS DISCREPANCY CHECK ═══\n"
        "After collecting the detail page data:\n"
        "1. Click the 'Filing History' button in the bottom right of the page\n"
        "2. A new page opens showing all filings for the entity\n"
        "3. For each filing record, click the CAMERA BUTTON on the right side "
        "of the filing row — this opens a detail snapshot below with tabs\n"
        "4. Select the 'Officer Information' tab in each snapshot\n"
        "5. Compare the officer addresses in the snapshot against the addresses "
        "already collected from the main detail page\n"
        "6. For ANY address that differs from what was previously collected, "
        "add it to the person's address list as a hyphen-separated value:\n"
        "  '123 Main St, Las Vegas, NV - 125 Main St, Las Vegas, NV'\n"
        "7. Repeat for each filing in the history\n\n"
        "Only after checking all filing snapshots for address discrepancies "
        "can the agent consider the mission successful."
    ),

    # ─── NEW HAMPSHIRE ─────────────────────────────────────────
    "NH": (
        "The New Hampshire QuickStart Business Inquiry portal at "
        "quickstart.sos.nh.gov/online/BusinessInquire.\n\n"
        "SEARCH: Radio buttons at top for search type:\n"
        "- 'Business Name' (default — use this)\n"
        "- 'Business ID'\n"
        "- 'Filing Number'\n"
        "- 'Registered Agent'\n"
        "Match type options: 'Starts With', 'Contains', 'Exact Match', 'All Words'. "
        "Use 'Contains' for broadest matching.\n\n"
        "CAPTCHA: There is a CAPTCHA that must be completed before searching. "
        "If it cannot be solved, fall back to Google search.\n\n"
        "RESULTS: A table showing Business Name, Business ID, Home State, "
        "Business Type, Registered Agent Name, and Status. NOTE: the results "
        "table itself shows the Registered Agent — useful for quick scanning.\n\n"
        "DETAIL PAGE: Shows entity name, status, formation date, renewal dates, "
        "principal/mailing addresses, registered agent details.\n"
        "- Registered Agent: directly on the detail page\n"
        "- OFFICERS: NOT on the main detail page overview. Officers are in "
        "FILED DOCUMENTS — you must look at the Filing History section and "
        "open the most recent Annual Report filing. Corporations list officers "
        "and directors in annual reports. LLCs list members/managers.\n\n"
        "FALLBACK: If CAPTCHA blocks search, use Google: "
        "'\"entity name\" site:sos.nh.gov'."
    ),

    # ─── NEW JERSEY ────────────────────────────────────────────
    "NJ": (
        "New Jersey has TWO search portals:\n"
        "1. njportal.com/dor/businessnamesearch/ — simple free name search\n"
        "2. njportal.com/dor/businessrecords/ — full service with Status Reports\n\n"
        "SEARCH: Enter the entity name in the Business Name field. Other search "
        "options include Principal Name, Registered Agent, or Entity ID. "
        "Click 'Search'.\n\n"
        "RESULTS: A list showing business name, entity type, status, and ID. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: The free detail page shows:\n"
        "- Entity Name, Type, Status, Formation/Registration Date\n"
        "- Registered Agent: name and address\n"
        "- Principal Office address\n"
        "- Business ID\n\n"
        "OFFICERS — CRITICAL LIMITATION: Full officer/director/manager lists "
        "require ordering a 'Status Report' which is a PAID service (a few "
        "dollars per report). The free detail page only shows the registered "
        "agent. Extract the registered agent and note that NJ requires paid "
        "Status Reports for full officer data.\n\n"
        "ALTERNATIVE: Use the 'Principal Name' search to check if a known "
        "person is associated with an entity (reverse lookup). Also try Google: "
        "'\"entity name\" New Jersey officers directors'."
    ),

    # ─── NEW MEXICO ────────────────────────────────────────────
    "NM": (
        "The New Mexico SOS search is at enterprise.sos.nm.gov/search. The page "
        "loads with a search bar in the center of the page.\n\n"

        "═══ SEARCH ═══\n"
        "Below the search bar is a dropdown for 'Advanced Search' — IGNORE this. "
        "The advanced options do not add value given the information available.\n\n"
        "1. Input the entity name directly into the search bar\n"
        "2. Click the search button on the right side of the input box\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "A tabular view of results appears below the search bar.\n"
        "- Select the record that is an EXACT match to the search query\n"
        "- If no exact match, select the CLOSEST possible match\n"
        "- Click the blue box containing the entity name\n\n"

        "═══ DETAIL SIDEBAR — EXTRACT EVERYTHING ═══\n"
        "A sidebar section opens on the RIGHT side of the screen with entity "
        "details. Extract ALL of the following:\n"
        "- Entity Status\n"
        "- Registered Agent Name\n"
        "- Registered Agent Address\n"
        "- Manager(s)/Member(s) names and titles (if listed)\n\n"

        "NOTE: The New Mexico portal does NOT allow the public to download "
        "filing documents. The sidebar data is all that is available. Once "
        "the above information has been gathered, the agent's job is complete "
        "for this entity — do not attempt to find filing downloads."
    ),

    # ─── NEW YORK ──────────────────────────────────────────────
    "NY": (
        "The New York DOS search redirects from the old appext20.dos.ny.gov URL "
        "to the newer portal at apps.dos.ny.gov/publicInquiry/.\n\n"
        "SEARCH: The form has:\n"
        "- Search type dropdown: 'Entity Name' (default), 'DOS ID', 'Assumed Name'\n"
        "- Text input for the entity name\n"
        "- Status filter dropdown: 'All Statuses' (use this for broadest results)\n"
        "- Match method: 'Begins With' (recommended), 'Contains', 'Base Word'\n"
        "- Entity type checkboxes: Corporation, LLC, LP, LLP — leave ALL checked\n"
        "Click 'Search'. Max 500 results returned.\n\n"
        "RESULTS: A table with Entity Name, DOS ID, Type, Status, Filing Date. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Shows entity name, DOS ID, type, status, filing date, "
        "county, jurisdiction.\n"
        "- Service of Process: address for legal papers\n"
        "- Registered Agent: name and address (if designated)\n\n"
        "OFFICERS — SEVERELY LIMITED: New York does NOT provide a full officer "
        "list online for free. For business corporations, ONLY the CEO name/address "
        "may be shown. For LLCs, NO officer/member data is available. Full officer "
        "lists require ordering copies of filed documents (PAID service).\n\n"
        "STRATEGY: Extract the registered agent and CEO (if corporation). "
        "Supplement with Google search: '\"entity name\" New York officers directors'. "
        "No CAPTCHA on this portal."
    ),

    # ─── NORTH CAROLINA ───────────────────────────────────────
    "NC": (
        "The North Carolina SOS search at sosnc.gov may block automated requests. "
        "In a real browser, navigate to the search page.\n\n"
        "SEARCH: The page has a text input for entity name. Type the entity "
        "name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: North Carolina shows:\n"
        "- Entity Name, SOS ID, Type, Status (Current-Active, etc.)\n"
        "- Date Filed, Citizenship (Domestic/Foreign)\n"
        "- Registered Agent: name and address in a clearly labeled section\n"
        "- Principal Office address\n"
        "- OFFICERS: North Carolina lists officers on the detail page under "
        "'Officers' or 'Directors'. Each has Name, Title, and Address. "
        "Scroll down to find this section."
    ),

    # ─── NORTH DAKOTA ──────────────────────────────────────────
    "ND": (
        "The North Dakota First Stop search at firststop.sos.nd.gov/search/business "
        "provides a simple search interface.\n\n"
        "SEARCH: Enter the entity name in the search text field and click "
        "'Search'. The page may have minimal controls.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: North Dakota shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Look for 'Officers', 'Commercial Registered Agent', "
        "or 'Governors' sections. North Dakota lists officers with Name, "
        "Title, and Address on the detail page."
    ),

    # ─── OHIO ──────────────────────────────────────────────────
    "OH": (
        "The Ohio SOS business search is at businesssearch.ohiosos.gov.\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Decide whether the record provided is a business entity name or a "
        "person's name.\n"
        "- If it is a business name (most likely): use the Entity Name flow below\n"
        "- If it is a person's name: adapt the search accordingly\n\n"

        "═══ ENTITY NAME SEARCH ═══\n"
        "1. Enter the entity name into the business name search input box "
        "in the center of the page\n"
        "2. Click the 'Search' button\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "A tabular view of all potential entity matches appears at the bottom "
        "of the screen under the 'Search Results' section.\n"
        "- Identify the EXACT match to the entity name\n"
        "- If no exact match, find the CLOSEST possible match\n"
        "- Click the 'Show Details' button on the right side of the result row\n\n"

        "═══ DETAIL POPUP — INITIAL EXTRACTION ═══\n"
        "A popup page appears with entity details. Extract:\n"
        "- Entity Status\n"
        "- Registered Agent Name\n"
        "- Registered Agent Address\n\n"

        "═══ FILING SECTION — DOWNLOAD ALL FILES ═══\n"
        "Scroll down on the popup page to the filing section. This section lists "
        "all filings for the entity.\n\n"
        "For EACH filing row:\n"
        "1. Click the 'Download Image' URL on the right side of the filing row\n"
        "2. Download and open the document\n"
        "3. Extract the following from each document:\n"
        "   - Any officers, agents, or associates listed — record their name, "
        "title, and address\n"
        "   - This includes people who may have had a PAST association with the "
        "entity (former officers, prior agents, etc.) — record these as well\n\n"

        "═══ ADDRESS DISCREPANCY CHECK — CRITICAL ═══\n"
        "After downloading and reviewing ALL filing documents:\n"
        "- Compare addresses for each person across all filings\n"
        "- If a person's address differs between filings, capture ALL variants "
        "as a hyphen-separated list:\n"
        "  '123 Main St, Columbus, OH - 456 Oak Ave, Columbus, OH'\n"
        "- Also record any officers or associates found in older filings who "
        "do NOT appear in the most recent filing — these are former associates "
        "who still have value for downstream enrichment\n\n"
        "Only after downloading and reviewing ALL filing documents can the agent "
        "consider this job successful."
    ),

    # ─── OKLAHOMA ──────────────────────────────────────────────
    "OK": (
        "The Oklahoma SOS search at sos.ok.gov/corp/corpInquiryFind.aspx "
        "has a straightforward interface.\n\n"
        "SEARCH: The page has:\n"
        "- 'Entity Name' text input field — type the entity name\n"
        "- A 'Search' button next to it\n"
        "- An 'Advanced Search>>' link (ignore for basic searches)\n"
        "- Cloudflare Turnstile CAPTCHA may appear — complete it if shown\n"
        "Click 'Search' after entering the name.\n\n"
        "RESULTS: Results display below with clickable filing numbers. "
        "Click the filing number or entity name for the closest match.\n\n"
        "DETAIL PAGE: Oklahoma shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Filing\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Oklahoma lists officers on the detail page. Look for "
        "'Officers', 'Directors', or 'Managers' section. Each has Name, "
        "Title, and Address."
    ),

    # ─── OREGON ────────────────────────────────────────────────
    "OR": (
        "The Oregon SOS search is at egov.sos.state.or.us/br/"
        "pkg_web_name_srch_inq.login. The page loads with a 'Business Name' "
        "input box in the top left quadrant of the screen. On the left side "
        "of the page under 'Associated Business Search' text are two hyperlinks:\n"
        "- 'By Business'\n"
        "- 'By Individual'\n\n"

        "═══ CHOOSING THE RIGHT SEARCH ═══\n"
        "Before making any input, decide whether the record provided is a "
        "business entity or a person's name.\n\n"
        "IF PERSON NAME:\n"
        "- Click the 'By Individual' hyperlink\n"
        "- Parse the individual's name into first and last name\n"
        "- Enter the names into the search bar on the new page\n"
        "- Click 'Search for Associated Names'\n"
        "- Proceed to review results as described below\n\n"
        "IF BUSINESS ENTITY (most likely):\n"
        "- Stay on the initial page\n"
        "- Enter the entity name into the 'Business Name' search bar\n"
        "- Click 'Search for Business Name'\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "The page reloads with a tabular view of all matching results.\n"
        "- Select the hyperlinked entity name that is an EXACT match\n"
        "- If no exact match, select the CLOSEST possible match\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The page reloads with a comprehensive view of entity data in "
        "multiple tabular sections from top to bottom:\n\n"

        "SECTION 1 — BUSINESS ENTITY DATA:\n"
        "- This section contains general filing information\n"
        "- No critical data here — skip to the next section\n\n"

        "SECTION 2 — ASSOCIATED NAMES (CRITICAL — COLLECT ALL):\n"
        "This section contains ALL the important data. It is structured as "
        "multiple sub-sections, each representing a different associated party.\n\n"

        "PRINCIPAL PLACE OF BUSINESS (first sub-section):\n"
        "- Contains the business address — COLLECT this\n\n"

        "REGISTERED AGENT sub-section:\n"
        "- Name fields are in SEPARATE CELLS: First Name | Middle Initial | "
        "Last Name\n"
        "- COMBINE these into one full name: 'First Middle Last'\n"
        "- Address fields are also in SEPARATE CELLS: Street Address | City | "
        "State | Zip\n"
        "- COMBINE these into one full address: 'Street, City, State Zip'\n"
        "- Record the combined name and combined address together\n\n"

        "OFFICER / MEMBER sub-sections (below Registered Agent):\n"
        "Each officer/member has the SAME cell-separated format:\n"
        "- NAME ROW: First Name | Middle Initial | Last Name — in separate cells\n"
        "  → Combine into one name: 'First Middle Last'\n"
        "- ADDRESS ROW: Street address line\n"
        "- ADDRESS 2 ROW: Secondary address line — SKIP this, do not collect\n"
        "- CSZ ROW: City | State | Zip — in separate cells\n"
        "  → Combine the street address + CSZ into one full address:\n"
        "    'Street Address, City, State Zip'\n\n"
        "EVERY single officer/member listed in this section MUST be collected. "
        "For each one, combine the cell-separated name into a single name "
        "and the cell-separated address into a single address, then add them "
        "to the XLSX.\n\n"

        "NOTE: No filing document downloads are needed for Oregon — all "
        "necessary data (agents, officers, addresses) is available directly "
        "in the tabular view on this page. Once all agent and officer info "
        "has been collected, the agent can consider this a success."
    ),

    # ─── PENNSYLVANIA ──────────────────────────────────────────
    "PA": (
        "The Pennsylvania DOS search at file.dos.pa.gov/search/business may "
        "block static requests. In a real browser it should load.\n\n"
        "SEARCH: Enter the entity name in the search field and click 'Search'. "
        "There may be filter options for entity type and status.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Pennsylvania shows:\n"
        "- Entity Name, Entity Number, Type, Status\n"
        "- Date of Incorporation\n"
        "- Registered Office address (Pennsylvania uses 'Registered Office' "
        "rather than 'Registered Agent')\n"
        "- OFFICERS: Pennsylvania lists officers on the detail page or in "
        "filing documents. Look for 'Officers' or 'Names' section. "
        "Each officer has Name, Title, and Address."
    ),

    # ─── RHODE ISLAND ──────────────────────────────────────────
    "RI": (
        "The Rhode Island SOS search at business.sos.ri.gov has a comprehensive "
        "search interface similar to Massachusetts.\n\n"
        "SEARCH: The page has 8 search methods with radio buttons. Use:\n"
        "- 'Entity Name' (first option, usually default)\n"
        "- Type the entity name in the text field\n"
        "- Search type dropdown: select 'Full text' or 'Contains' for "
        "broadest matching (options: 'Begins with', 'Exact match', "
        "'Full text', 'Soundex')\n"
        "- There are also 'Active'/'Inactive' radio buttons — select 'Active' "
        "first (try 'Inactive' if no results)\n"
        "- Click 'Submit'\n\n"
        "RESULTS: A table of entities. Click the entity name.\n\n"
        "DETAIL PAGE: Rhode Island shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address (searchable via 'Agent' tab)\n"
        "- OFFICERS: Look for officers listed on the detail page. "
        "Rhode Island includes Name, Title, and Address for each officer."
    ),

    # ─── SOUTH CAROLINA ────────────────────────────────────────
    "SC": (
        "The South Carolina SOS search at businessfilings.sc.gov has a "
        "clean search interface.\n\n"
        "SEARCH: The page shows:\n"
        "- A 'Search Type' dropdown with options: 'Begins With', 'Contains', "
        "'Exact Match' — select 'Contains' for broadest matching\n"
        "- A text input field for the business name\n"
        "- A 'Search' button\n"
        "- CAPTCHA verification may be required for repeated searches\n"
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: Matching entities appear below. Click the entity name.\n\n"
        "DETAIL PAGE (called 'Profile Page'): South Carolina shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Incorporation/Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: South Carolina lists officers on the profile page. "
        "Look for 'Officers/Directors' or 'Managers/Members' section.\n"
        "- An 'Add Filing' button appears for existing businesses — ignore it."
    ),

    # ─── SOUTH DAKOTA ──────────────────────────────────────────
    "SD": (
        "The South Dakota SOS search at sosenterprise.sd.gov has a clean form.\n\n"
        "SEARCH: The 'Business Information Search' form has:\n"
        "- A text input for name search with dropdown: 'Starts With' or "
        "'Contains' — select 'Contains'\n"
        "- A 'Business ID' field — ignore\n"
        "- An 'Active Entities Only' checkbox — leave CHECKED initially "
        "(uncheck if no results)\n"
        "- 'Clear' button (resets form) and 'Search' button\n"
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: South Dakota shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: South Dakota lists officers on the detail page. "
        "Look for 'Principals' or 'Officers' section. Each has Name, "
        "Title, and Address."
    ),

    # ─── TENNESSEE ─────────────────────────────────────────────
    "TN": (
        "The Tennessee BEAR system at tnbear.tn.gov may be slow to load. "
        "Wait for the page to fully render.\n\n"
        "SEARCH: The page has:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- Search type filter may be available\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, Control Number, "
        "Type, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Tennessee shows:\n"
        "- Entity Name, Control Number, Type, Status\n"
        "- Date of Formation, Duration\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Tennessee lists officers on the detail page. Look for "
        "'Principals' or 'Officers/Directors' section. Officers have Name, "
        "Title, and Address. Scroll down to find this section."
    ),

    # ─── TEXAS ─────────────────────────────────────────────────
    "TX": (
        "IMPORTANT: Texas has TWO separate systems:\n"
        "1. Comptroller (franchise tax status): comptroller.texas.gov\n"
        "2. SOS (entity filings): https://www.sos.state.tx.us/corp/sosda/index.shtml\n\n"
        "The given URL redirects to the Comptroller's franchise tax search at "
        "comptroller.texas.gov/taxes/franchise/account-status/search.\n\n"
        "COMPTROLLER SEARCH (franchise tax):\n"
        "- Three mutually exclusive fields (use only one):\n"
        "  1. 'Taxpayer Number' — ignore\n"
        "  2. 'Entity Name' — type the entity name here (2-50 characters)\n"
        "  3. 'Texas SOS File Number' — ignore\n"
        "- Click 'Submit'\n\n"
        "RESULTS: A table with Name, Taxpayer Number, and Zip Code. "
        "Entity names are clickable links. Click the matching entity.\n\n"
        "DETAIL PAGE (Comptroller): Shows franchise tax status, entity name, "
        "and address, but DOES NOT show officers.\n\n"
        "FOR OFFICERS: Navigate to the Texas SOS direct access at "
        "https://www.sos.state.tx.us/corp/sosda/index.shtml — search by "
        "entity name. The SOS filing documents contain officer information. "
        "Look for 'Registered Agent' and officer names in the filing details.\n\n"
        "OFFICERS: Texas does NOT list officers in a simple table on either "
        "portal. Officer data is embedded in filing documents. Extract the "
        "Registered Agent name and address from the SOS record. For full "
        "officer details, check the Certificate of Formation or most recent "
        "annual/periodic report filing."
    ),

    # ─── UTAH ──────────────────────────────────────────────────
    "UT": (
        "The Utah business registration portal redirects to "
        "businessregistration.utah.gov. The page may show a login screen.\n\n"
        "SEARCH: Look for the 'Search' menu in the navigation bar. "
        "Click 'Search' then 'Business Entity' from the dropdown. "
        "Alternatively, click the 'Search Business Entity Records' button "
        "on the main page — it does NOT require login.\n\n"
        "On the search page, enter the entity name in the text field "
        "and click 'Search'.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Utah shows:\n"
        "- Entity Name, Entity Number, Type, Status (Active/Expired)\n"
        "- Date of Formation/Registration\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Utah lists officers on the detail page. Look for "
        "'Officers', 'Directors', 'Members', or 'Managers' section. "
        "Each has Name, Title, and Address."
    ),

    # ─── VERMONT ───────────────────────────────────────────────
    "VT": (
        "The Vermont business filings portal at bizfilings.vermont.gov may "
        "be an Angular app that loads slowly. Wait for full render.\n\n"
        "SEARCH: Look for a 'Business Name' text input or search bar. "
        "Type the entity name and submit.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Vermont shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Vermont lists officers on the detail page. Look for "
        "'Officers/Directors' or 'Members/Managers' section."
    ),

    # ─── VIRGINIA ──────────────────────────────────────────────
    "VA": (
        "The Virginia SCC entity search at cis.scc.virginia.gov/EntitySearch "
        "provides the search interface.\n\n"
        "SEARCH: The page has:\n"
        "- 'Entity Name' text input — type the entity name\n"
        "- 'Entity ID' field — ignore\n"
        "- Search type may default to 'Begins With' — change to 'Contains' "
        "if available\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, ID, Type, Status. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Virginia shows:\n"
        "- Entity Name, SCC ID, Type, Status (Active/Inactive/Cancelled)\n"
        "- Date of Formation, State of Formation\n"
        "- Registered Agent: name and FULL address\n"
        "- Principal Office address\n"
        "- OFFICERS: Virginia lists officers on the detail page under "
        "'Officers/Directors' or 'Principal Office'. Each officer has Name, "
        "Title, and Address. Check for 'Annual Report' filings which may "
        "have the most recent officer list."
    ),

    # ─── WASHINGTON ────────────────────────────────────────────
    "WA": (
        "The Washington CCFS portal at ccfs.sos.wa.gov loads a JavaScript app. "
        "The title says 'Corporations and Charities System'. Wait for full render.\n\n"
        "SEARCH: Look for a search bar or 'Business Name' input at the top. "
        "Type the entity name and click 'Search' or press Enter.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Washington shows:\n"
        "- Entity Name, UBI Number, Type, Status\n"
        "- Date of Formation/Registration\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Washington lists 'Governors' (their term for officers) "
        "on the detail page. Look for 'Governors' section which shows "
        "Name, Title, and Address for each."
    ),

    # ─── WEST VIRGINIA ─────────────────────────────────────────
    "WV": (
        "The West Virginia SOS search at apps.sos.wv.gov/business/corporations "
        "has a search interface with two fields.\n\n"
        "SEARCH: The page has:\n"
        "- 'Organization' text field — type the entity name here\n"
        "- 'Agent/Officer/Name' text field — can be used for person searches\n"
        "- A 'Show Advanced Search Options' link for more filters\n"
        "- TIP: Use '%' as a wildcard if you have trouble finding a match "
        "(e.g., '%Desert Taco%')\n"
        "Click the search button or press Enter.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: West Virginia shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent/Representative: name and address\n"
        "- OFFICERS: West Virginia lists officers on the detail page. "
        "Look for 'Officers/Directors' or 'Principal' section."
    ),

    # ─── WISCONSIN ─────────────────────────────────────────────
    "WI": (
        "The Wisconsin DFI search at apps.wi.gov/CorpSearch may show a CAPTCHA "
        "or security page. Complete the CAPTCHA if presented.\n\n"
        "SEARCH: Once past any CAPTCHA, look for:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Wisconsin shows:\n"
        "- Entity Name, Entity ID, Type, Status\n"
        "- Date of Filing\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Wisconsin lists officers on the detail page. Look for "
        "'Officers' or 'Directors/Members' section with Name, Title, "
        "and Address for each."
    ),

    # ─── WYOMING ───────────────────────────────────────────────
    "WY": (
        "The Wyoming SOS search at wyobiz.wyo.gov may show a CAPTCHA page. "
        "Complete the visual CAPTCHA if presented (it asks 'What code is "
        "in the image?' with a text input).\n\n"
        "SEARCH: Once past the CAPTCHA, look for:\n"
        "- 'Filing Name' or 'Business Name' text input — type the entity name\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Wyoming shows:\n"
        "- Entity Name, Filing ID, Type, Status (Active/Inactive)\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Wyoming lists officers on the detail page. Look for "
        "'Officers', 'Directors', or 'Members/Managers' section with Name, "
        "Title, and Address."
    ),

    # ─── DISTRICT OF COLUMBIA ──────────────────────────────────
    "DC": (
        "The DC business search is at corponline.dlcp.dc.gov/homepage/"
        "business-search. The page loads with a search input box.\n\n"

        "═══ SEARCH ═══\n"
        "1. Enter the entity name into the search input box\n"
        "2. Click the blue 'Search' button in the bottom right corner\n\n"

        "═══ CAPTCHA HANDLING ═══\n"
        "A reCAPTCHA modal may pop up after clicking search. If it does:\n"
        "1. Click the 'I am not a robot' checkbox\n"
        "2. Click 'Submit'\n"
        "If this reCAPTCHA appears at ANY point during the search process, "
        "handle it the same way — click the checkbox and submit.\n\n"

        "═══ SEARCH RESULTS ═══\n"
        "A tabular view of all matching entities appears below.\n"
        "- Select the entity name that is an EXACT match to the record "
        "provided for search\n"
        "- If no exact match, select the closest possible match\n\n"

        "═══ DETAIL PAGE — EXTRACT EVERYTHING ═══\n"
        "The entity detail page loads with information in sections from "
        "top to bottom:\n\n"
        "TOP SECTION:\n"
        "- Entity Status — COLLECT this\n"
        "- Street Address — COLLECT this (this is the business address)\n\n"
        "REGISTERED AGENT INFORMATION SECTION:\n"
        "- Registered Agent Name — COLLECT this\n"
        "- Registered Agent Address — COLLECT this\n\n"
        "BENEFICIAL OWNER INFORMATION SECTION (Officers):\n"
        "- This section lists the Beneficial Owners of the entity\n"
        "- These are the OFFICERS — record them as such on the XLSX\n"
        "- For EACH beneficial owner, collect:\n"
        "  * Name\n"
        "  * Address\n"
        "- Every beneficial owner MUST be collected\n\n"
        "Once all status, address, registered agent, and beneficial owner "
        "data has been collected, the agent can consider the job complete."
    ),
}
