"""
Per-state SOS portal navigation instructions for browser-use agents.
Each entry provides step-by-step directions tailored to that state's
specific page layout so the LLM-driven browser agent can reliably
find the search box, submit a query, click the right result, and
locate officers/agents on the detail page.
"""

PORTAL_INSTRUCTIONS: dict[str, str] = {

    # ─── ALABAMA ───────────────────────────────────────────────
    "AL": (
        "The Alabama SOS search page at arc-sos.state.al.us/cgi/corpname.mbr "
        "is the name-search form. You will see a text field labeled 'Entity Name' "
        "and a Search button. Enter the entity name and click Search.\n\n"
        "RESULTS: A table of matching entities appears with columns for Entity "
        "Name, ID Number, and Status. Click the entity name link that most "
        "closely matches your search.\n\n"
        "DETAIL PAGE: The detail page shows entity information in labeled rows:\n"
        "- Entity Name, Entity ID, Entity Type, Formation Date, Status near the top\n"
        "- Registered Agent name and address in a distinct section\n"
        "- Principal Address section\n"
        "- OFFICERS: Look for an 'Officers' or 'Officials' section below the "
        "entity summary. Officers are listed with Name, Title, and Address. "
        "If not visible, look for a link or tab labeled 'Officers' or 'Principals' "
        "and click it.\n\n"
        "IMPORTANT: Alabama sometimes lists officers on the same page as the "
        "entity details — scroll down past the registered agent section to find them."
    ),

    # ─── ALASKA ────────────────────────────────────────────────
    "AK": (
        "The Alaska CBPL search page has two search fields at the top of the page:\n"
        "1. 'Entity Number' — ignore this field\n"
        "2. 'Entity Name' — type the entity name here\n\n"
        "Below the Entity Name field are two radio buttons:\n"
        "- 'Starts With' (default)\n"
        "- 'Contains'\n"
        "Select 'Contains' for broader matching, then click the Search button.\n\n"
        "SIDEBAR NOTE: The left sidebar has links to search by Officials, Agents, "
        "etc. Ignore these — use the main Entity Name search.\n\n"
        "RESULTS: A table appears with entity names, numbers, and status. "
        "Click the entity name link for the closest match.\n\n"
        "DETAIL PAGE: The detail page shows:\n"
        "- Entity name, type, status, and formation date at the top\n"
        "- Registered Agent: name and address in a labeled section\n"
        "- OFFICERS: Look for an 'Officials' section. Alaska lists officers "
        "by Name, Title, and Address. This is typically on the same detail page. "
        "Scroll down to find all officials listed."
    ),

    # ─── ARIZONA ───────────────────────────────────────────────
    "AZ": (
        "The Arizona Corporation Commission search is at ecorp.azcc.gov. "
        "If the page loads to EntitySearch/Index, you will see a search form.\n\n"
        "SEARCH: There is a text input field for 'Entity Name'. Type the entity "
        "name. There may be a dropdown for search type — leave it on the default "
        "(typically 'Contains' or 'Starts With'). Click the 'Search' button.\n\n"
        "RESULTS: A table of matching entities appears. Columns include Entity "
        "Name, File Number, Type, and Status. Click the entity name or file number "
        "link for the closest match.\n\n"
        "DETAIL PAGE: The detail page shows entity information in sections:\n"
        "- Entity Name, Type, Status (Active/Inactive), Formation Date at top\n"
        "- Statutory Agent (this is Arizona's term for Registered Agent): "
        "name and address\n"
        "- Principal Address\n"
        "- OFFICERS: Look for 'Officers/Directors/Managers/Members' section. "
        "Arizona calls this section differently based on entity type:\n"
        "  - For LLCs: 'Members' or 'Managers'\n"
        "  - For Corps: 'Officers and Directors'\n"
        "  This may be a separate tab or expandable section. CLICK any tab labeled "
        "'Officers', 'Directors', 'Members', 'Managers', or 'Annual Reports'. "
        "Officers are listed with Name, Title, and Address."
    ),

    # ─── ARKANSAS ──────────────────────────────────────────────
    "AR": (
        "The Arkansas SOS search redirects to sos-corp-search.ark.org/corps. "
        "The page shows 'Search Incorporations, Cooperatives, Banks and Insurance "
        "Companies' at the top.\n\n"
        "SEARCH FORM (top to bottom):\n"
        "1. 'Corporation Type' dropdown — leave on 'All Types'\n"
        "2. 'Name' text field — type the entity name here (this is the primary search)\n"
        "3. 'Fictitious Name' — ignore\n"
        "4. 'Registered Agent (RA)' — ignore\n"
        "5. 'RA City' — ignore\n"
        "6. 'RA State' dropdown — ignore (leave on 'Any State')\n"
        "7. 'Filing #' — ignore\n"
        "Click the 'Search' button below the form.\n\n"
        "RESULTS: Matching entities appear in a list below the form. "
        "Click the entity name that most closely matches.\n\n"
        "DETAIL PAGE: Shows entity details including:\n"
        "- Filing number, entity name, type, status, formation date\n"
        "- Registered Agent name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Look for 'Officers', 'Directors', or 'Principals' section. "
        "Arkansas lists officers on the detail page — scroll down past the "
        "registered agent info. Each officer has Name, Title, and Address."
    ),

    # ─── CALIFORNIA ────────────────────────────────────────────
    "CA": (
        "The California bizfile portal at bizfileonline.sos.ca.gov/search/business "
        "has bot protection that may show a 'Please stand by' interstitial. Wait for "
        "it to resolve — the page will load automatically after a few seconds.\n\n"
        "Once the page loads, scroll down to the BOTTOM of the page. At the very "
        "bottom you will find a search box — this is the main entity search input. "
        "The search box has a filter that defaults to 'Contains (Keywords)' which "
        "is correct — do NOT change it or use the Advanced Search option.\n\n"
        "Type the entity name into the search box and click Search or press Enter.\n\n"
        "RESULTS: Matching entities appear below the search box. Scroll down slightly "
        "to see them. Each result shows the entity name in a blue clickable box, "
        "along with entity number and status. Click the blue box containing the "
        "entity name that best matches your search.\n\n"
        "MODAL: After clicking an entity name, a pop-out modal appears on the "
        "RIGHT side of the screen with 3 buttons:\n"
        "- 'Request Certificate' at the top — IGNORE this\n"
        "- 'Request Access' on the bottom left — IGNORE this\n"
        "- 'View History' on the bottom right — CLICK THIS BUTTON\n\n"
        "FILING HISTORY PAGE: After clicking 'View History', a page loads showing "
        "multiple filing document dropdowns ordered from most recent (top) to "
        "oldest (bottom). Scroll to the VERY BOTTOM to find the initial filing "
        "document (Statement of Information or Articles of Organization/Incorporation).\n\n"
        "From the INITIAL FILING document, extract:\n"
        "- Agent for Service of Process: name, address, city, state, zip\n"
        "- Corporate/LLC address (principal office)\n\n"
        "OFFICERS: California does NOT always list officers on the SOS portal "
        "directly. Officers are found in the 'Statement of Information' (SI) "
        "filings. Look for the MOST RECENT 'SI' filing in the filing history — "
        "this contains CEO/CFO/Secretary names for corporations or Manager/Member "
        "names for LLCs. Click to open/download the SI document and extract the "
        "officer names, titles, and addresses from it.\n\n"
        "If no SI filing is available, the Agent for Service of Process from the "
        "initial filing is the only person record available."
    ),

    # ─── COLORADO ──────────────────────────────────────────────
    "CO": (
        "The Colorado SOS search is at sos.state.co.us/biz. The page shows "
        "'Business Entity Search' with a search form.\n\n"
        "SEARCH FORM:\n"
        "- 'Entity Name' text field — type the entity name here\n"
        "- There may be additional fields for Entity ID — ignore them\n"
        "- Search type may default to 'Beginning' — change to 'Contains' if "
        "available for broader matching\n"
        "- Click 'Search' or 'Submit'\n\n"
        "RESULTS: A table of matching entities with Name, ID, Status, "
        "Formation Date, and Entity Type. Click the entity name link.\n\n"
        "DETAIL PAGE: Colorado's detail page is comprehensive:\n"
        "- Entity name, ID, type, status at top\n"
        "- Formation/Registration date\n"
        "- Principal Office address\n"
        "- Registered Agent: name and address in a labeled section\n"
        "- OFFICERS: Scroll down for 'Principals' or 'Officers' section. "
        "Colorado often uses a table showing each principal's Name, "
        "Role/Title, and Address. This is on the same page — just scroll down. "
        "Also check if there's a 'History' link showing past annual report "
        "filings which may list updated officer information."
    ),

    # ─── CONNECTICUT ───────────────────────────────────────────
    "CT": (
        "The Connecticut search is at service.ct.gov/business — this is a "
        "Salesforce-based portal. The page may take a moment to load.\n\n"
        "SEARCH: Look for a search bar or 'Business Search' input field. "
        "The interface uses a step-based wizard with tabs. You want the "
        "'Business Name Search' option. Enter the entity name and submit.\n\n"
        "RESULTS: Results appear in a list or card format showing entity name, "
        "type, and status. Click the matching entity.\n\n"
        "DETAIL PAGE: Shows entity details including:\n"
        "- Business Name, Business ID, Entity Type, Status\n"
        "- Date of Incorporation/Formation\n"
        "- Registered Agent/Statutory Agent name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Connecticut typically lists officers on the detail page. "
        "Look for 'Officers', 'Directors', or 'Managers' section. Scroll down "
        "through the full detail page. Officers include Name, Title, and Address."
    ),

    # ─── DELAWARE ──────────────────────────────────────────────
    "DE": (
        "The Delaware Division of Corporations search at icis.corp.delaware.gov "
        "may block non-browser requests. With a real browser it should load.\n\n"
        "SEARCH: The page has a search form with:\n"
        "- 'Entity Name' text input — type the entity name\n"
        "- 'File Number' text input — ignore this\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table shows matching entities with Name, File Number, "
        "Incorporation Date, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Delaware's detail page shows:\n"
        "- Entity Name, File Number, Status (Good Standing/Void/etc.)\n"
        "- Incorporation Date, Entity Type\n"
        "- Registered Agent: name and address\n"
        "- IMPORTANT: Delaware does NOT publicly list officers/directors on "
        "their SOS portal. The only person you can get is the Registered Agent. "
        "Officer information is only available via paid certified copy. Record "
        "the Registered Agent and note that Delaware does not disclose officers online."
    ),

    # ─── FLORIDA ───────────────────────────────────────────────
    "FL": (
        "The Florida Sunbiz portal at search.sunbiz.org may have bot protection. "
        "Wait for the page to fully load.\n\n"
        "SEARCH: The page 'Search by Entity Name' has:\n"
        "- A large text input field for the entity name at the top\n"
        "- A 'Search Now' button to the right of the input\n"
        "Type the entity name and click 'Search Now'.\n\n"
        "RESULTS: A table appears listing matching entities with Document Number, "
        "Entity Name, Status, and Filing Date. Entity names are clickable blue links. "
        "Click the entity name that most closely matches.\n\n"
        "DETAIL PAGE: Florida provides one of the most comprehensive detail pages:\n"
        "- Entity Name, Filing Date, Status (Active/Inactive/Dissolved)\n"
        "- FEI/EIN Number\n"
        "- Date Filed, State of Formation, Last Event\n"
        "- Principal Address and Mailing Address\n"
        "- Registered Agent: name AND address clearly labeled\n"
        "- OFFICERS/DIRECTORS: Clearly labeled section below the registered "
        "agent. Lists each officer with:\n"
        "  - Title (President, Vice President, Director, Manager, etc.)\n"
        "  - Name\n"
        "  - Address\n"
        "  ALL officers are on this same page — no tabs to click. Just scroll "
        "down past the registered agent section.\n\n"
        "- Annual Reports section at the bottom shows filing history."
    ),

    # ─── GEORGIA ───────────────────────────────────────────────
    "GA": (
        "The Georgia SOS search at ecorp.sos.ga.gov/BusinessSearch may have "
        "bot protection. Wait for the page to load.\n\n"
        "SEARCH: The page has a search form with:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- 'Business Type' dropdown — leave on 'All' or default\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities shows Business Name, Control Number, "
        "Filing Type, and Status. Click the entity name or control number link.\n\n"
        "DETAIL PAGE: Georgia's detail page shows:\n"
        "- Business Name, Control Number, Business Type, Status\n"
        "- Date of Formation/Registration\n"
        "- Principal Office address\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Georgia lists officers in a section called 'Principals' or "
        "'Officers/Directors'. Each entry shows Name, Title, and Address. "
        "This is on the main detail page — scroll down to find it.\n"
        "- Also check for 'Annual Registration' filings which may have updated "
        "officer lists."
    ),

    # ─── HAWAII ────────────────────────────────────────────────
    "HI": (
        "The Hawaii Business Express (HBE) portal at hbe.ehawaii.gov may redirect "
        "to a login page. If you see a login page, look for a 'Search' or "
        "'Public Search' link that does NOT require login.\n\n"
        "SEARCH: The page has a search box with a dropdown to the RIGHT of it. "
        "Change the dropdown from 'Begins with' to 'Contains' for broader matching. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table appears with business names as blue clickable links, "
        "plus filing info columns. Click the matching business name.\n\n"
        "DETAIL PAGE: The detail page has a 'General Info' section showing:\n"
        "- Entity status, standing, contact information\n"
        "- Registered Agent: name and address — on the main page\n"
        "- OFFICERS: Listed on the main detail page with all addresses. "
        "Trade names, trademarks, and service marks also shown.\n"
        "All officer data is on ONE page — no tabs needed.\n\n"
        "NOTE: Hawaii uses DCCA (Dept of Commerce & Consumer Affairs), not "
        "'Secretary of State'."
    ),

    # ─── IDAHO ─────────────────────────────────────────────────
    "ID": (
        "The Idaho SOS search redirects from sos.idaho.gov/search-business to "
        "sosbiz.idaho.gov/search/business/ — the browser will land there.\n\n"
        "SEARCH: The page has a search text input. By default it searches by "
        "business name. Click the 'Advanced' dropdown/toggle to expand options — "
        "this reveals radio buttons for 'Begins with' and 'Contains'. "
        "Select 'Contains' for broader matching. Type the entity name and "
        "click 'Search'.\n\n"
        "RESULTS — SPLIT-PANE LAYOUT: Results appear in a table on the LEFT "
        "side of the page. Each result shows business name, status, entity type, "
        "and filing number.\n\n"
        "DETAIL — RIGHT PANEL: Click a business name in the results. A detail "
        "panel appears on the RIGHT side of the page (NO full page navigation). "
        "This panel shows entity status, formation date, registered agent, "
        "officers/members/managers, and entity history.\n\n"
        "IMPORTANT: The detail loads in a right-side panel — do NOT expect a "
        "full page navigation. Read the officer data from the right panel while "
        "results remain on the left."
    ),

    # ─── ILLINOIS ──────────────────────────────────────────────
    "IL": (
        "The Illinois SOS search redirects from apps.ilsos.gov/corporatellc to "
        "apps.ilsos.gov/businessentitysearch/. With a real browser it should load.\n\n"
        "SEARCH: The page has a search text input where you can enter a full name, "
        "partial name, or File Number. The search supports entity name, registered "
        "agent, president, secretary, manager, file number, or keyword. "
        "Type the entity name and click the search button.\n\n"
        "RESULTS: A table with columns: Status (Active, Dissolved, Not Good Standing), "
        "File Number, Entity Name, and Type (LLC, Corporation, etc.). "
        "Click the entity name or file number link.\n\n"
        "DETAIL PAGE — CRITICAL TABBED INTERFACE:\n"
        "The detail page uses TABS. You MUST click the correct tab:\n"
        "- Tab 1 (default): General info — status, type, formation date, "
        "registered agent name and address, principal office\n"
        "- Tab 2: 'Manager' tab (for LLCs) or 'Officer' tab (for Corporations) — "
        "THIS IS WHERE OFFICER DATA LIVES. Shows each manager/officer's title, "
        "name, and address. YOU MUST CLICK THIS TAB.\n"
        "- Tab 3: Previous names of the entity\n"
        "- Tab 4: Assumed names (DBAs)\n"
        "- Tab 5: Series information\n\n"
        "The registered agent is on Tab 1. Officers/managers are on Tab 2. "
        "The tab label changes based on entity type: 'Manager' for LLCs, "
        "'Officer' for Corporations."
    ),

    # ─── INDIANA ───────────────────────────────────────────────
    "IN": (
        "The Indiana INBiz portal at bsd.sos.in.gov/publicbusinesssearch "
        "has a comprehensive search interface.\n\n"
        "SEARCH (Quick Search section at top):\n"
        "- Radio buttons for search mode: 'Contains', 'Starts With', 'Exact Match' "
        "— select 'Contains'\n"
        "- Input fields below: 'Business Name', 'Business ID', 'Filing Number', "
        "'Registered Agent Name', 'Incorporator or Governing Person Name'\n"
        "- Type the entity name in the 'Business Name' field\n"
        "- There may be a CAPTCHA — complete it if shown\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table of matching entities with Name, Entity Type, Status, "
        "and State. Click the entity name link.\n\n"
        "DETAIL PAGE: Indiana shows everything on ONE page:\n"
        "- Business ID, Creation Date, Jurisdiction, Status\n"
        "- Principal Office address\n"
        "- Registered Agent: name and address (typically near the bottom)\n"
        "- OFFICERS: Indiana uses the term 'Governing Persons' instead of "
        "'Officers' or 'Managers'. The Governing Persons section lists each "
        "owner/officer/member with Name, Title, and Address — all on the main "
        "detail page. No tabs needed.\n"
        "- Buttons in the bottom right provide access to filing history and "
        "document images."
    ),

    # ─── IOWA ──────────────────────────────────────────────────
    "IA": (
        "The Iowa SOS search at sos.iowa.gov/search/business redirects to "
        "sos.iowa.gov/search/business/search.aspx.\n\n"
        "SEARCH: The page has TWO search boxes — only one can be used at a time:\n"
        "- First search box: search by business entity NAME — use this one\n"
        "- Second search box: search by FILING NUMBER — ignore this\n"
        "Type the entity name into the FIRST search box. The system auto-strips "
        "noise words like 'THE', 'AN' from the front and 'CORPORATION', 'INC' "
        "from the end. Click the Search button NEXT TO the name field (each "
        "search box has its own Search button).\n\n"
        "RESULTS: A table with columns: Business No., Name, Status, Type. "
        "Click the business name or number link.\n\n"
        "DETAIL PAGE — CRITICAL TABBED INTERFACE:\n"
        "The detail page uses TABS across the top. You MUST click multiple tabs:\n"
        "- 'Summary' tab: basic entity info, status, formation date\n"
        "- 'Address' tab: principal office address\n"
        "- 'Agent' tab: registered agent name and address — CLICK THIS TAB\n"
        "- 'Filings' tab: filing history\n"
        "- 'Names' tab: previous and assumed names\n"
        "- 'Officers' tab: officer and director names, titles, addresses — "
        "CLICK THIS TAB\n"
        "- 'Stock' tab: stock info (if applicable)\n\n"
        "Officers are NOT on the default Summary tab. You MUST click the "
        "'Officers' tab and the 'Agent' tab separately."
    ),

    # ─── KANSAS ────────────────────────────────────────────────
    "KS": (
        "The Kansas SOS business entity search is at "
        "sos.ks.gov/eforms/BusinessEntity/Search.aspx.\n\n"
        "SEARCH: The page has a text input for 'Business Entity Name'. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities with Name, Type, Status, "
        "and Filing Date. Click the entity name.\n\n"
        "DETAIL PAGE: Kansas shows:\n"
        "- Entity Name, Type, Status, Formation Date\n"
        "- Registered Agent: name, address (under 'Resident Agent')\n"
        "- Principal Office address\n"
        "- OFFICERS: Kansas lists officers/directors in a section below the "
        "entity summary. Each entry has Name, Title, and Address. "
        "Scroll down on the detail page to find officers."
    ),

    # ─── KENTUCKY ──────────────────────────────────────────────
    "KY": (
        "The Kentucky SOS business entity search is at "
        "sosbes.sos.ky.gov/BusSearchNProfile/search.aspx.\n\n"
        "SEARCH: The page has:\n"
        "- A dropdown to select search type: 'Business Name or Organization Number', "
        "'City Name of principal office', or 'Zip Codes'\n"
        "- Leave on 'Business Name or Organization Number'\n"
        "- A text input field — type the entity name\n"
        "- A checkbox 'Show active entities only' — leave it CHECKED for initial "
        "search (uncheck if no results)\n"
        "- An 'Advanced Search' link for more options — typically not needed\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table of matching entities. Click the entity name link.\n\n"
        "DETAIL PAGE: Kentucky shows:\n"
        "- Entity Name, Organization Number, Type, Status\n"
        "- Filing Date, Standing (Good Standing/Not Good Standing)\n"
        "- Registered Agent: name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Look for 'Current Representatives' or 'Officers' section. "
        "Kentucky lists each officer with Name, Title, and Address. This may "
        "be on the main detail page — scroll down to find it."
    ),

    # ─── LOUISIANA ─────────────────────────────────────────────
    "LA": (
        "The Louisiana SOS search at "
        "coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx shows "
        "'Search for Louisiana Business Filings'.\n\n"
        "SEARCH: The page offers three search methods:\n"
        "1. 'Entity Name Search' — type the full entity name here (primary method)\n"
        "2. 'Charter/Registration Number Search' — ignore\n"
        "3. 'Officer/Agent Name Search' — use for PERSON searches (has first/last fields)\n\n"
        "IMPORTANT: There is a CHECKBOX for human verification that MUST be "
        "checked BEFORE clicking Search. It may be a simple checkbox or a "
        "reCAPTCHA widget. Check it, then click 'Search'.\n\n"
        "RESULTS: A table shows matching entities with business name, entity type, "
        "city, status, and a 'Details' button. Click the 'Details' button on the "
        "matching row.\n\n"
        "DETAIL PAGE: Louisiana shows everything on ONE page:\n"
        "- Charter Number, Entity Name, Type, Status\n"
        "- Formation/Incorporation Date\n"
        "- Registered Agent: name AND full address\n"
        "- Registered Office location\n"
        "- OFFICERS: Louisiana lists officers, directors, members, AND managers "
        "in separate categories — check ALL of them. Names with titles and "
        "addresses are on the main detail page. No tabs needed.\n"
        "- Filing history at the bottom."
    ),

    # ─── MAINE ─────────────────────────────────────────────────
    "ME": (
        "The Maine ICRS (Interactive Corporate Records System) at "
        "icrs.informe.org may also be at apps3.web.maine.gov — both host "
        "the same system.\n\n"
        "SEARCH: The page has two search fields:\n"
        "- 'Keyword from name to be searched' — type the entity name here "
        "(searches legal name, former names, assumed names, and fictitious "
        "names simultaneously)\n"
        "- 'Charter number' — ignore this\n"
        "Click the search button.\n\n"
        "RESULTS: A table with Charter Number, Legal Name, Entity Type, "
        "Filing Type, and Status. Click the entity name or charter number.\n\n"
        "DETAIL PAGE: Maine shows on ONE page:\n"
        "- Charter Number, Legal Name, Entity Type, Status\n"
        "- Formation Date\n"
        "- IMPORTANT: Maine uses 'Clerk' instead of 'Registered Agent' for "
        "domestic corporations. Foreign entities use 'Registered Agent'. "
        "Look for BOTH terms — name and address are on the main page.\n"
        "- Principal/home office address\n"
        "- OFFICERS: Officers and directors are on the main detail page. "
        "Each has Name, Title, and Address.\n"
        "- Filing history and document images at the bottom."
    ),

    # ─── MARYLAND ──────────────────────────────────────────────
    "MD": (
        "The Maryland Business Express portal at "
        "egov.maryland.gov/BusinessExpress/EntitySearch has the search interface.\n\n"
        "SEARCH: The page shows three search options with radio buttons:\n"
        "- 'Business Name' (default — use this)\n"
        "- 'Department ID'\n"
        "- 'Employer Identification Number (EIN)'\n"
        "Select 'Business Name', type the entity name in the text field, "
        "and click the Search button.\n\n"
        "RESULTS: Matching entities appear below. Click the entity name "
        "that most closely matches.\n\n"
        "DETAIL PAGE: Maryland shows:\n"
        "- Entity Name, Department ID, Status (Active/Forfeited/etc.)\n"
        "- Date of Formation, Entity Type\n"
        "- Resident Agent: name and address (Maryland uses 'Resident Agent' "
        "instead of 'Registered Agent')\n"
        "- Principal Office address\n"
        "- OFFICERS: Maryland may list officers or direct you to view "
        "annual report filings. Look for 'Officers' or 'Principal Members' "
        "section. If not visible, check filing documents for officer data."
    ),

    # ─── MASSACHUSETTS ─────────────────────────────────────────
    "MA": (
        "The Massachusetts Corporations Search at "
        "corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx has "
        "multiple search options.\n\n"
        "SEARCH: The page shows four radio buttons at top:\n"
        "- 'Entity Name' (default — use this for business searches)\n"
        "- 'Individual Name' (use for person name searches)\n"
        "- 'Identification Number'\n"
        "- 'Filing Number'\n\n"
        "For ENTITY searches:\n"
        "- Select 'Entity Name'\n"
        "- Type the entity name in the 'Enter name:' text field\n"
        "- Search type dropdown: select 'Full text' for broadest matching "
        "(options: 'Begins with', 'Exact match', 'Full text', 'Soundex')\n"
        "- Click 'Search'\n\n"
        "For PERSON searches:\n"
        "- Select 'Individual Name'\n"
        "- Fill in First, Middle, Last name fields\n"
        "- Click 'Search'\n\n"
        "RESULTS: A table of matching entities with Name, ID, Type, Status. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Massachusetts shows:\n"
        "- Entity Name, ID Number, Type, Status\n"
        "- Date of Organization\n"
        "- Registered Agent: name and address (may say 'Resident Agent')\n"
        "- Principal Office\n"
        "- OFFICERS: Massachusetts lists officers/directors in the detail view. "
        "Look for 'Officers' tab or section. Each officer has Name, Title, "
        "and Residential Address. Click any available tab to see officers."
    ),

    # ─── MICHIGAN ──────────────────────────────────────────────
    "MI": (
        "The Michigan LARA search at cofs.lara.state.mi.us may not respond "
        "to static fetches. With a real browser it should load.\n\n"
        "SEARCH: The page layout is similar to Massachusetts (ASP.NET CorpSearch). "
        "Look for:\n"
        "- 'Entity Name' radio button and text input\n"
        "- Search type dropdown (Begins with, Contains, etc.)\n"
        "- 'Search' button\n"
        "Type the entity name and click Search.\n\n"
        "RESULTS: A table with Name, ID, Type, Status. Click the entity name.\n\n"
        "DETAIL PAGE: Michigan shows:\n"
        "- Entity Name, ID Number, Type, Status\n"
        "- Date of Formation, Jurisdiction\n"
        "- Resident Agent: name and address\n"
        "- OFFICERS: Michigan lists officers on the detail page. Look for "
        "'Officers/Directors' or 'Managers/Members' section. Click any "
        "available tab for officer details."
    ),

    # ─── MINNESOTA ─────────────────────────────────────────────
    "MN": (
        "The Minnesota SOS portal redirects to mblsportal.sos.mn.gov/Business/Search. "
        "Use this URL directly.\n\n"
        "SEARCH: Look for a 'Business Name' text input. Type the entity name "
        "and click 'Search'.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Minnesota shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date Filed, Home Jurisdiction\n"
        "- Registered Agent/Office: name and address\n"
        "- Principal Office address\n"
        "- OFFICERS: Minnesota may list officers on the detail page or in "
        "a separate 'Annual Report' section. Look for 'Principals', "
        "'Officers', or 'Managers' section and scroll down."
    ),

    # ─── MISSISSIPPI ───────────────────────────────────────────
    "MS": (
        "The Mississippi SOS search may return 404 on the given URL. "
        "Try navigating to https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessNameSearch "
        "or the main page at https://corp.sos.ms.gov and look for 'Business Search'.\n\n"
        "SEARCH: Enter the entity name in the 'Business Name' field "
        "and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Mississippi shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Mississippi lists officers on the detail page. Look for "
        "'Officers', 'Directors', or 'Members' section with Name, Title, "
        "and Address for each."
    ),

    # ─── MISSOURI ──────────────────────────────────────────────
    "MO": (
        "The Missouri SOS search at bsd.sos.mo.gov/BusinessEntity/BESearch "
        "may block automated requests. Wait for the page to load.\n\n"
        "SEARCH: The page has:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- Search type options may include 'Starts With', 'Contains'\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, Charter Number, "
        "Type, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Missouri shows:\n"
        "- Entity Name, Charter Number, Type, Status\n"
        "- Formation Date, Purpose\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Missouri typically lists officers directly on the "
        "detail page. Look for 'Officers/Directors' section showing "
        "Name, Title, and Address. Scroll down past the registered agent info."
    ),

    # ─── MONTANA ───────────────────────────────────────────────
    "MT": (
        "The Montana SOS search at biz.sos.mt.gov/search may not respond "
        "to static fetches but should work in a real browser.\n\n"
        "SEARCH: Look for a text input for 'Business Name'. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Montana shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Montana lists officers on the detail page. Look for "
        "'Officers' or 'Principals' section with Name, Title, and Address."
    ),

    # ─── NEBRASKA ──────────────────────────────────────────────
    "NE": (
        "The Nebraska SOS Corporate and Business Search is at "
        "www.nebraska.gov/sos/corp/corpsearch.cgi.\n\n"
        "SEARCH: The form has radio buttons at top for search type:\n"
        "- 'Name Starts With' (default — safest choice)\n"
        "- 'Name Keyword Search' (more forgiving for partial matches)\n"
        "- 'Name Sounds Like'\n"
        "- 'Name Exact Match'\n"
        "Select a radio button, then type the entity name in the text field.\n\n"
        "CAPTCHA: A Google reCAPTCHA ('I'm not a robot' checkbox) appears "
        "below the search field. This is MANDATORY — complete it before "
        "clicking 'Perform Search'.\n\n"
        "RESULTS: A table showing 25 per page: Company Name, SOS Account Number, "
        "Business Type, Status. Click the company name or 'Details' link.\n\n"
        "DETAIL PAGE: Shows entity name, SOS Account Number, formation date, "
        "next filing due, status, entity type.\n"
        "- Registered Agent: name and address shown on the free detail page\n"
        "- OFFICERS: LIMITED — Nebraska's free online search primarily shows "
        "the registered agent. Full officer/director lists are in Annual Report "
        "documents which require a FEE. Extract the registered agent and note "
        "that full officers require paid document access.\n\n"
        "FALLBACK: If the CAPTCHA cannot be solved, use Google search: "
        "'\"entity name\" site:nebraska.gov secretary of state'."
    ),

    # ─── NEVADA ────────────────────────────────────────────────
    "NV": (
        "The Nevada SilverFlume Business Entity Search at esos.nv.gov may have "
        "Incapsula bot protection — wait for any interstitial to resolve.\n\n"
        "SEARCH: The form has three text input fields at top:\n"
        "- 'Entity Name' — type the entity name here\n"
        "- 'NV Business ID' — ignore\n"
        "- 'Entity Number' — ignore\n\n"
        "Below the Entity Name field are four radio buttons for matching:\n"
        "- 'Starts With' (default — use this)\n"
        "- 'Contains'\n"
        "- 'Exact Match'\n"
        "- 'All Words'\n"
        "Include the full entity suffix (LLC, Inc) for precise matching. "
        "Leave Entity Type and Status filters on 'All'. Click 'Search'.\n\n"
        "RESULTS: A table with Entity Name, Status, Type, Formation Date, "
        "NV Business ID, Entity Number. Click the entity name.\n\n"
        "DETAIL PAGE: Nevada shows comprehensive info — NO CAPTCHA:\n"
        "- Entity Name, Type, Status, Formation Date, NV Business ID\n"
        "- Registered Agent: name AND address directly on the page\n"
        "- OFFICERS: Officers/directors/managers are on the MAIN detail page — "
        "no tabs needed. Scroll down to find them. There may be a 'Show Officer "
        "History' checkbox to expand historical officers. Officer data comes "
        "from the most recent annual list filing."
    ),

    # ─── NEW HAMPSHIRE ─────────────────────────────────────────
    "NH": (
        "The New Hampshire QuickStart Business Inquiry portal at "
        "quickstart.sos.nh.gov/online/BusinessInquire.\n\n"
        "SEARCH: Radio buttons at top for search type:\n"
        "- 'Business Name' (default — use this)\n"
        "- 'Business ID'\n"
        "- 'Filing Number'\n"
        "- 'Registered Agent'\n"
        "Match type options: 'Starts With', 'Contains', 'Exact Match', 'All Words'. "
        "Use 'Contains' for broadest matching.\n\n"
        "CAPTCHA: There is a CAPTCHA that must be completed before searching. "
        "If it cannot be solved, fall back to Google search.\n\n"
        "RESULTS: A table showing Business Name, Business ID, Home State, "
        "Business Type, Registered Agent Name, and Status. NOTE: the results "
        "table itself shows the Registered Agent — useful for quick scanning.\n\n"
        "DETAIL PAGE: Shows entity name, status, formation date, renewal dates, "
        "principal/mailing addresses, registered agent details.\n"
        "- Registered Agent: directly on the detail page\n"
        "- OFFICERS: NOT on the main detail page overview. Officers are in "
        "FILED DOCUMENTS — you must look at the Filing History section and "
        "open the most recent Annual Report filing. Corporations list officers "
        "and directors in annual reports. LLCs list members/managers.\n\n"
        "FALLBACK: If CAPTCHA blocks search, use Google: "
        "'\"entity name\" site:sos.nh.gov'."
    ),

    # ─── NEW JERSEY ────────────────────────────────────────────
    "NJ": (
        "New Jersey has TWO search portals:\n"
        "1. njportal.com/dor/businessnamesearch/ — simple free name search\n"
        "2. njportal.com/dor/businessrecords/ — full service with Status Reports\n\n"
        "SEARCH: Enter the entity name in the Business Name field. Other search "
        "options include Principal Name, Registered Agent, or Entity ID. "
        "Click 'Search'.\n\n"
        "RESULTS: A list showing business name, entity type, status, and ID. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: The free detail page shows:\n"
        "- Entity Name, Type, Status, Formation/Registration Date\n"
        "- Registered Agent: name and address\n"
        "- Principal Office address\n"
        "- Business ID\n\n"
        "OFFICERS — CRITICAL LIMITATION: Full officer/director/manager lists "
        "require ordering a 'Status Report' which is a PAID service (a few "
        "dollars per report). The free detail page only shows the registered "
        "agent. Extract the registered agent and note that NJ requires paid "
        "Status Reports for full officer data.\n\n"
        "ALTERNATIVE: Use the 'Principal Name' search to check if a known "
        "person is associated with an entity (reverse lookup). Also try Google: "
        "'\"entity name\" New Jersey officers directors'."
    ),

    # ─── NEW MEXICO ────────────────────────────────────────────
    "NM": (
        "The New Mexico SOS search at enterprise.sos.nm.gov/search may redirect "
        "to enterprise.sos.nm.gov/search/business.\n\n"
        "SEARCH: A dropdown defaults to 'Entity Name/DBA Name' — leave it. "
        "Match type options: 'Contains' (broadest), 'Starts With', "
        "'Name Availability'. Use 'Contains'. An 'Advanced' button expands "
        "filters for Entity Type, Status, and Registration Date range. "
        "Enter the entity name and click the magnifying glass or press Enter.\n\n"
        "RESULTS: A list of matching entities. Click the entity name.\n\n"
        "DETAIL — SLIDE-OUT PANEL: The detail appears as a slide-out panel "
        "(NOT a full page navigation). The panel shows:\n"
        "- Entity Name, Control Number, Type, Status\n"
        "- Formation Date\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Officers/members/managers are shown directly in the "
        "detail panel. No tabs or paid reports needed — New Mexico shows "
        "officer data for free.\n"
        "- Filing history at the bottom.\n\n"
        "NOTE: The detail is a slide-out panel, not a new page. Read the "
        "data from the panel while results remain visible."
    ),

    # ─── NEW YORK ──────────────────────────────────────────────
    "NY": (
        "The New York DOS search redirects from the old appext20.dos.ny.gov URL "
        "to the newer portal at apps.dos.ny.gov/publicInquiry/.\n\n"
        "SEARCH: The form has:\n"
        "- Search type dropdown: 'Entity Name' (default), 'DOS ID', 'Assumed Name'\n"
        "- Text input for the entity name\n"
        "- Status filter dropdown: 'All Statuses' (use this for broadest results)\n"
        "- Match method: 'Begins With' (recommended), 'Contains', 'Base Word'\n"
        "- Entity type checkboxes: Corporation, LLC, LP, LLP — leave ALL checked\n"
        "Click 'Search'. Max 500 results returned.\n\n"
        "RESULTS: A table with Entity Name, DOS ID, Type, Status, Filing Date. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Shows entity name, DOS ID, type, status, filing date, "
        "county, jurisdiction.\n"
        "- Service of Process: address for legal papers\n"
        "- Registered Agent: name and address (if designated)\n\n"
        "OFFICERS — SEVERELY LIMITED: New York does NOT provide a full officer "
        "list online for free. For business corporations, ONLY the CEO name/address "
        "may be shown. For LLCs, NO officer/member data is available. Full officer "
        "lists require ordering copies of filed documents (PAID service).\n\n"
        "STRATEGY: Extract the registered agent and CEO (if corporation). "
        "Supplement with Google search: '\"entity name\" New York officers directors'. "
        "No CAPTCHA on this portal."
    ),

    # ─── NORTH CAROLINA ───────────────────────────────────────
    "NC": (
        "The North Carolina SOS search at sosnc.gov may block automated requests. "
        "In a real browser, navigate to the search page.\n\n"
        "SEARCH: The page has a text input for entity name. Type the entity "
        "name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: North Carolina shows:\n"
        "- Entity Name, SOS ID, Type, Status (Current-Active, etc.)\n"
        "- Date Filed, Citizenship (Domestic/Foreign)\n"
        "- Registered Agent: name and address in a clearly labeled section\n"
        "- Principal Office address\n"
        "- OFFICERS: North Carolina lists officers on the detail page under "
        "'Officers' or 'Directors'. Each has Name, Title, and Address. "
        "Scroll down to find this section."
    ),

    # ─── NORTH DAKOTA ──────────────────────────────────────────
    "ND": (
        "The North Dakota First Stop search at firststop.sos.nd.gov/search/business "
        "provides a simple search interface.\n\n"
        "SEARCH: Enter the entity name in the search text field and click "
        "'Search'. The page may have minimal controls.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: North Dakota shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Look for 'Officers', 'Commercial Registered Agent', "
        "or 'Governors' sections. North Dakota lists officers with Name, "
        "Title, and Address on the detail page."
    ),

    # ─── OHIO ──────────────────────────────────────────────────
    "OH": (
        "The Ohio SOS business search at businesssearch.ohiosos.gov may "
        "block static fetches. In a real browser it should load.\n\n"
        "SEARCH: Look for a 'Business Name' text input. Type the entity name "
        "and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Ohio shows:\n"
        "- Entity Name, Charter Number, Type, Status\n"
        "- Filing Date, Expiration Date\n"
        "- Statutory Agent (Ohio's term for Registered Agent): name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Ohio lists officers in the filing documents. Look for "
        "an 'Officers' section or check the most recent filing/annual report. "
        "Officers have Name, Title, and Address."
    ),

    # ─── OKLAHOMA ──────────────────────────────────────────────
    "OK": (
        "The Oklahoma SOS search at sos.ok.gov/corp/corpInquiryFind.aspx "
        "has a straightforward interface.\n\n"
        "SEARCH: The page has:\n"
        "- 'Entity Name' text input field — type the entity name\n"
        "- A 'Search' button next to it\n"
        "- An 'Advanced Search>>' link (ignore for basic searches)\n"
        "- Cloudflare Turnstile CAPTCHA may appear — complete it if shown\n"
        "Click 'Search' after entering the name.\n\n"
        "RESULTS: Results display below with clickable filing numbers. "
        "Click the filing number or entity name for the closest match.\n\n"
        "DETAIL PAGE: Oklahoma shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Filing\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Oklahoma lists officers on the detail page. Look for "
        "'Officers', 'Directors', or 'Managers' section. Each has Name, "
        "Title, and Address."
    ),

    # ─── OREGON ────────────────────────────────────────────────
    "OR": (
        "The Oregon SOS search at egov.sos.state.or.us may show a security "
        "error page. If blocked, try the alternative URL: "
        "https://sos.oregon.gov/business/Pages/find.aspx and look for the "
        "'Business Name Search' link.\n\n"
        "SEARCH: Once on the search page:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- Click 'Search' or 'Submit'\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Oregon shows:\n"
        "- Entity Name, Registry Number, Type, Status\n"
        "- Date of Registration\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Oregon may list officers in 'Associated Names' or "
        "'Officers/Directors' section. Look for names with roles like "
        "President, Secretary, Director, Member, Manager."
    ),

    # ─── PENNSYLVANIA ──────────────────────────────────────────
    "PA": (
        "The Pennsylvania DOS search at file.dos.pa.gov/search/business may "
        "block static requests. In a real browser it should load.\n\n"
        "SEARCH: Enter the entity name in the search field and click 'Search'. "
        "There may be filter options for entity type and status.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Pennsylvania shows:\n"
        "- Entity Name, Entity Number, Type, Status\n"
        "- Date of Incorporation\n"
        "- Registered Office address (Pennsylvania uses 'Registered Office' "
        "rather than 'Registered Agent')\n"
        "- OFFICERS: Pennsylvania lists officers on the detail page or in "
        "filing documents. Look for 'Officers' or 'Names' section. "
        "Each officer has Name, Title, and Address."
    ),

    # ─── RHODE ISLAND ──────────────────────────────────────────
    "RI": (
        "The Rhode Island SOS search at business.sos.ri.gov has a comprehensive "
        "search interface similar to Massachusetts.\n\n"
        "SEARCH: The page has 8 search methods with radio buttons. Use:\n"
        "- 'Entity Name' (first option, usually default)\n"
        "- Type the entity name in the text field\n"
        "- Search type dropdown: select 'Full text' or 'Contains' for "
        "broadest matching (options: 'Begins with', 'Exact match', "
        "'Full text', 'Soundex')\n"
        "- There are also 'Active'/'Inactive' radio buttons — select 'Active' "
        "first (try 'Inactive' if no results)\n"
        "- Click 'Submit'\n\n"
        "RESULTS: A table of entities. Click the entity name.\n\n"
        "DETAIL PAGE: Rhode Island shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address (searchable via 'Agent' tab)\n"
        "- OFFICERS: Look for officers listed on the detail page. "
        "Rhode Island includes Name, Title, and Address for each officer."
    ),

    # ─── SOUTH CAROLINA ────────────────────────────────────────
    "SC": (
        "The South Carolina SOS search at businessfilings.sc.gov has a "
        "clean search interface.\n\n"
        "SEARCH: The page shows:\n"
        "- A 'Search Type' dropdown with options: 'Begins With', 'Contains', "
        "'Exact Match' — select 'Contains' for broadest matching\n"
        "- A text input field for the business name\n"
        "- A 'Search' button\n"
        "- CAPTCHA verification may be required for repeated searches\n"
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: Matching entities appear below. Click the entity name.\n\n"
        "DETAIL PAGE (called 'Profile Page'): South Carolina shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Incorporation/Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: South Carolina lists officers on the profile page. "
        "Look for 'Officers/Directors' or 'Managers/Members' section.\n"
        "- An 'Add Filing' button appears for existing businesses — ignore it."
    ),

    # ─── SOUTH DAKOTA ──────────────────────────────────────────
    "SD": (
        "The South Dakota SOS search at sosenterprise.sd.gov has a clean form.\n\n"
        "SEARCH: The 'Business Information Search' form has:\n"
        "- A text input for name search with dropdown: 'Starts With' or "
        "'Contains' — select 'Contains'\n"
        "- A 'Business ID' field — ignore\n"
        "- An 'Active Entities Only' checkbox — leave CHECKED initially "
        "(uncheck if no results)\n"
        "- 'Clear' button (resets form) and 'Search' button\n"
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: South Dakota shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: South Dakota lists officers on the detail page. "
        "Look for 'Principals' or 'Officers' section. Each has Name, "
        "Title, and Address."
    ),

    # ─── TENNESSEE ─────────────────────────────────────────────
    "TN": (
        "The Tennessee BEAR system at tnbear.tn.gov may be slow to load. "
        "Wait for the page to fully render.\n\n"
        "SEARCH: The page has:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- Search type filter may be available\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, Control Number, "
        "Type, and Status. Click the entity name.\n\n"
        "DETAIL PAGE: Tennessee shows:\n"
        "- Entity Name, Control Number, Type, Status\n"
        "- Date of Formation, Duration\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Tennessee lists officers on the detail page. Look for "
        "'Principals' or 'Officers/Directors' section. Officers have Name, "
        "Title, and Address. Scroll down to find this section."
    ),

    # ─── TEXAS ─────────────────────────────────────────────────
    "TX": (
        "IMPORTANT: Texas has TWO separate systems:\n"
        "1. Comptroller (franchise tax status): comptroller.texas.gov\n"
        "2. SOS (entity filings): https://www.sos.state.tx.us/corp/sosda/index.shtml\n\n"
        "The given URL redirects to the Comptroller's franchise tax search at "
        "comptroller.texas.gov/taxes/franchise/account-status/search.\n\n"
        "COMPTROLLER SEARCH (franchise tax):\n"
        "- Three mutually exclusive fields (use only one):\n"
        "  1. 'Taxpayer Number' — ignore\n"
        "  2. 'Entity Name' — type the entity name here (2-50 characters)\n"
        "  3. 'Texas SOS File Number' — ignore\n"
        "- Click 'Submit'\n\n"
        "RESULTS: A table with Name, Taxpayer Number, and Zip Code. "
        "Entity names are clickable links. Click the matching entity.\n\n"
        "DETAIL PAGE (Comptroller): Shows franchise tax status, entity name, "
        "and address, but DOES NOT show officers.\n\n"
        "FOR OFFICERS: Navigate to the Texas SOS direct access at "
        "https://www.sos.state.tx.us/corp/sosda/index.shtml — search by "
        "entity name. The SOS filing documents contain officer information. "
        "Look for 'Registered Agent' and officer names in the filing details.\n\n"
        "OFFICERS: Texas does NOT list officers in a simple table on either "
        "portal. Officer data is embedded in filing documents. Extract the "
        "Registered Agent name and address from the SOS record. For full "
        "officer details, check the Certificate of Formation or most recent "
        "annual/periodic report filing."
    ),

    # ─── UTAH ──────────────────────────────────────────────────
    "UT": (
        "The Utah business registration portal redirects to "
        "businessregistration.utah.gov. The page may show a login screen.\n\n"
        "SEARCH: Look for the 'Search' menu in the navigation bar. "
        "Click 'Search' then 'Business Entity' from the dropdown. "
        "Alternatively, click the 'Search Business Entity Records' button "
        "on the main page — it does NOT require login.\n\n"
        "On the search page, enter the entity name in the text field "
        "and click 'Search'.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Utah shows:\n"
        "- Entity Name, Entity Number, Type, Status (Active/Expired)\n"
        "- Date of Formation/Registration\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Utah lists officers on the detail page. Look for "
        "'Officers', 'Directors', 'Members', or 'Managers' section. "
        "Each has Name, Title, and Address."
    ),

    # ─── VERMONT ───────────────────────────────────────────────
    "VT": (
        "The Vermont business filings portal at bizfilings.vermont.gov may "
        "be an Angular app that loads slowly. Wait for full render.\n\n"
        "SEARCH: Look for a 'Business Name' text input or search bar. "
        "Type the entity name and submit.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: Vermont shows:\n"
        "- Entity Name, Filing Number, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Vermont lists officers on the detail page. Look for "
        "'Officers/Directors' or 'Members/Managers' section."
    ),

    # ─── VIRGINIA ──────────────────────────────────────────────
    "VA": (
        "The Virginia SCC entity search at cis.scc.virginia.gov/EntitySearch "
        "provides the search interface.\n\n"
        "SEARCH: The page has:\n"
        "- 'Entity Name' text input — type the entity name\n"
        "- 'Entity ID' field — ignore\n"
        "- Search type may default to 'Begins With' — change to 'Contains' "
        "if available\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities with Name, ID, Type, Status. "
        "Click the entity name.\n\n"
        "DETAIL PAGE: Virginia shows:\n"
        "- Entity Name, SCC ID, Type, Status (Active/Inactive/Cancelled)\n"
        "- Date of Formation, State of Formation\n"
        "- Registered Agent: name and FULL address\n"
        "- Principal Office address\n"
        "- OFFICERS: Virginia lists officers on the detail page under "
        "'Officers/Directors' or 'Principal Office'. Each officer has Name, "
        "Title, and Address. Check for 'Annual Report' filings which may "
        "have the most recent officer list."
    ),

    # ─── WASHINGTON ────────────────────────────────────────────
    "WA": (
        "The Washington CCFS portal at ccfs.sos.wa.gov loads a JavaScript app. "
        "The title says 'Corporations and Charities System'. Wait for full render.\n\n"
        "SEARCH: Look for a search bar or 'Business Name' input at the top. "
        "Type the entity name and click 'Search' or press Enter.\n\n"
        "RESULTS: Matching entities appear in a list. Click the entity name.\n\n"
        "DETAIL PAGE: Washington shows:\n"
        "- Entity Name, UBI Number, Type, Status\n"
        "- Date of Formation/Registration\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Washington lists 'Governors' (their term for officers) "
        "on the detail page. Look for 'Governors' section which shows "
        "Name, Title, and Address for each."
    ),

    # ─── WEST VIRGINIA ─────────────────────────────────────────
    "WV": (
        "The West Virginia SOS search at apps.sos.wv.gov/business/corporations "
        "has a search interface with two fields.\n\n"
        "SEARCH: The page has:\n"
        "- 'Organization' text field — type the entity name here\n"
        "- 'Agent/Officer/Name' text field — can be used for person searches\n"
        "- A 'Show Advanced Search Options' link for more filters\n"
        "- TIP: Use '%' as a wildcard if you have trouble finding a match "
        "(e.g., '%Desert Taco%')\n"
        "Click the search button or press Enter.\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: West Virginia shows:\n"
        "- Entity Name, ID, Type, Status\n"
        "- Date of Formation\n"
        "- Registered Agent/Representative: name and address\n"
        "- OFFICERS: West Virginia lists officers on the detail page. "
        "Look for 'Officers/Directors' or 'Principal' section."
    ),

    # ─── WISCONSIN ─────────────────────────────────────────────
    "WI": (
        "The Wisconsin DFI search at apps.wi.gov/CorpSearch may show a CAPTCHA "
        "or security page. Complete the CAPTCHA if presented.\n\n"
        "SEARCH: Once past any CAPTCHA, look for:\n"
        "- 'Business Name' text input — type the entity name\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Wisconsin shows:\n"
        "- Entity Name, Entity ID, Type, Status\n"
        "- Date of Filing\n"
        "- Registered Agent: name and address\n"
        "- Principal Office\n"
        "- OFFICERS: Wisconsin lists officers on the detail page. Look for "
        "'Officers' or 'Directors/Members' section with Name, Title, "
        "and Address for each."
    ),

    # ─── WYOMING ───────────────────────────────────────────────
    "WY": (
        "The Wyoming SOS search at wyobiz.wyo.gov may show a CAPTCHA page. "
        "Complete the visual CAPTCHA if presented (it asks 'What code is "
        "in the image?' with a text input).\n\n"
        "SEARCH: Once past the CAPTCHA, look for:\n"
        "- 'Filing Name' or 'Business Name' text input — type the entity name\n"
        "- 'Search' button\n\n"
        "RESULTS: A table of matching entities. Click the entity name.\n\n"
        "DETAIL PAGE: Wyoming shows:\n"
        "- Entity Name, Filing ID, Type, Status (Active/Inactive)\n"
        "- Date of Formation\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: Wyoming lists officers on the detail page. Look for "
        "'Officers', 'Directors', or 'Members/Managers' section with Name, "
        "Title, and Address."
    ),

    # ─── DISTRICT OF COLUMBIA ──────────────────────────────────
    "DC": (
        "The DC DCRA search at corponline.dcra.dc.gov/BizEntity.aspx may "
        "have availability issues (522 errors). Retry if the page fails "
        "to load initially.\n\n"
        "SEARCH: Once loaded, look for a 'Business Name' text input. "
        "Type the entity name and click 'Search'.\n\n"
        "RESULTS: Matching entities appear. Click the entity name.\n\n"
        "DETAIL PAGE: DC shows:\n"
        "- Entity Name, File Number, Type, Status\n"
        "- Date of Filing\n"
        "- Registered Agent: name and address\n"
        "- OFFICERS: DC lists officers on the detail page. Look for "
        "'Officers/Directors/Governors' section with Name, Title, "
        "and Address for each."
    ),
}
